### ISSUE TITLE
password recovery

### ISSUE THREAD

**Issue by innoticFR** [AlternC/AlternC#102]
Following the example of l'Autre Net (https://panel.lautre.net/sendpass.php), add a link to change the password.

The above link send a mail to the user with a url and a token to change the password.

**Comment by innoticFR** [comment]
Curiously there is m_mem::send_pass() function which means that this function was removed from a previous version

**Comment by lelutin** [comment]
@innoticFR @vincib we've been wanting such a feature in alternc for many years now. is there a way that we could somehow obtain the code that's in use at L'autre.net ?

**Comment by fser** [comment]
Of course. I didn't see your message before @lelutin.

**Comment by ddeenniiss** [comment]
A priori, ça fonctionne, testé sous 3.5.0~rc1+0~20190412204409.39~1 (dépôt koumbit)
