### ISSUE TITLE
"pcfg_openfile: unable to check htaccess file" with default permissions

### ISSUE THREAD

**Issue by innoticFR** [AlternC/AlternC#104]
The default permissions / ACL causes problem in Apache 2.4.10 to access .htaccess files

<code>
[Thu Jul 07 16:15:05.026795 2016] [core:crit] [pid 9526](13)Permission denied: [client x.x.x.x:59677] AH00529: /var/www/alternc/l/login/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/alternc/l/login/' is executable, referer: http://www.login.example.com/
</code>

The problem is similar to the one described there: https://lists.err.no/pipermail/mpm-itk/2014-June/000818.html

**Despite `AssignUserId`, .htaccess file is read using `www-data`user's permissions**

I resolved this one by adding user www-data to the acl in fixperms.sh.

For information, `posix_getpid()` and `posix_getgid()` under PHP returns the expected user uid.

**Comment by innoticFR** [comment]
Might be related to the use of NFS (http://mpm-itk.sesse.net/apache2.2-mpm-itk-2.2.17-01/CHANGES)

But it's unclear why this bug has not affected any other user of AlternC...

**Comment by innoticFR** [comment]
I have to test it, but i think i found the reason:

> EnableCapabilities (Apache 2.4 or newer only): Drop most root capabilities in the parent process, and instead run as the user given by the User/Group directives with some extra capabilities (in particular setuid). Somewhat more secure (especially when coupled with LimitUIDRange above), but can cause problems when serving from filesystems that do not honor capabilities, **such as NFS**.

I still have to test it.

Then it should be documented that people using NFS should disable this in their configuration by editing /etc/apache2/mods-enabled/mpm_itk.conf
`EnableCapabilities off`

**Comment by innoticFR** [comment]
Except that this option does not seem to exist:
   
> Invalid command 'EnableCapabilities', perhaps misspelled or defined by a module not included in the server configuration

**Comment by innoticFR** [comment]
OK. Current version for "libapache2-mpm-itk" in Debian jessie is "2.4.7-02-1.1+deb8u1"

The "EnableCapabilities" flag has been introduced in version 2.4.7-04

> mpm-itk 2.4.7-04, released 2016-02-14:
>
>  - Fix a compilation error on RHEL6; patch from Hans Kristian Rosbach.
>  - Add a new flag EnableCapabilities (default on), which can be disabled
    to revert to the behavior in place before 2.4.2-02, which causes problems
    when the filesystem in use does not respect capabilities (in particular
    NFS).
>  - Update copyright to 2016.

**Comment by vincib** [comment]
Adding www-data in the ACL seems to be a nice resolution of this bug without any security drawbacks I can think of. 
I'll port your fixperms.sh patch to stable-3.1 if you agree.

**Comment by petit42** [comment]
The problem with unable to protect directory in AlternC can be reproduce only for a directory create with ftp (true for 3.3.10 version of AlternC)
It seems there a problem with extend acl.
Diff of acl with a new directory create by FTP (protected directory is not possible), and the same directory after a fixperm (protected directory is possible):
< mask::r-x
< other::r-x
> mask::rwx
> other::---

**Comment by GuillaumeFromage** [comment]
> https://lists.err.no/pipermail/mpm-itk/2014-June/000818.html
> Despite AssignUserId, .htaccess file is read using www-datauser's permissions

Actually, that thread explicitly says that .htaccess is read with root privileges. By giving setfacl -m u:root:r on the .htaccess files, I can get everything to work as intended. It would be safe to make the parent dir d:u:root:r, so all is readable by root. This is quite confusing as a lot of shell tools let you go around permissions when you are root. I've installed stretch version of apache+mpm_itk, to be able to put EnableCapabilities off, but it didn't work. I'm running a 3 server cluster on 5.4 apache 2.2 shared over nfs with a 1 server apache 2.4 php 5.6 servers, and I can switch around sites without issues, by adding fixperms to update_domains and hacking fixperms a lot. I'll bring the pull requests over here after a couple of days in prod.

**Comment by innoticFR** [comment]
Why this ticket has been reopened?
