### ISSUE TITLE
Jessie : AlternC should allow HTTPS panel access for different host names

### ISSUE THREAD

**Issue by albancrommer** [AlternC/AlternC#106]
There is a hard filtering in the config PHP file for HTTPS calls to panel whose HOST does not match the AlternC panel HOSTNAME set in config.

With Letsencrypt, this is a bad thing : all domains now can have a HTTPS panel access.

**Comment by innoticFR** [comment]
This is a duplicate of https://github.com/AlternC/AlternC/issues/69
