### ISSUE TITLE
Jessie: AlternC should use the IncludeOptional directive

### ISSUE THREAD

**Issue by albancrommer** [AlternC/AlternC#108]
When injecting the generated vhosts, the simple Include command fails. 

```/etc/alternc/bureau.conf:36:  IncludeOptional /etc/alternc/apache-panel.d/*.conf```

Caution: this directive is STRICTLY restricted to Jessie only

Non blocking bug on the long term, but breaks a fresh install

**Comment by vincib** [comment]
fixed at 372a5bea39f2f82a56b81b9d573f764639f2c128
