### ISSUE TITLE
[File browser] Token invalid

### ISSUE THREAD

**Issue by pasoev** [AlternC/AlternC#111]
When editing a text for more than 30 minutes or so before saving it,
it makes error : the token is said "invalid" (not "expired"). It is a
very big trouble because all the work done on the text in this time is
lost and unless it was copy-pasted in advance there is no way to get
it back. There was no such problem in the old panel (on lautre.net
before upgrade) because even if session was lost which made it refuse
the post, the work could be saved anyway : either by repost (refresh
and confirm in this tab after login in another tab) or by the Back
button (the editor window was simple which let it take the edited
version of the content from the browser cache or something like this;
this was the only remaining possibility to save the edited text when
the internet connection is lost). Now none of these methods to avoid
losing the edited text work anymore.
The different changes which resulted in making those methods fail in
the new version can be criticized :
- the risk of CSRF attacks which motivated the introduction of token
protection is anyway very unlikely compared to the general risks of
losing an edited text by any kind of failure especially with a token
system, whose prevention should be considered priority;
- I appreciate that the edition rectangle is larger than before but I
don't see the motivation for the 2 tabs system (display/edition) which
seems to kill the possibility to get back the edited text by the Back
button.
So I ask for a solution to ensure that edited texts will never be lost
again: one thing is to correct the current error of lost token, but
even beyond this, in case there was any other problem with token
(maybe by very long wait: 2 hours wait before saving may happen ! or
user may log out by mistake and log in again) the reaction should
never be a total loss of the work done ! for example a redisplay of
posted version for repost would be great.
(I don't understand why token are needed to avoid CSRF attacks : maybe
it would need to change the web protocol but I think there should be a
way for a browser to promise that a post using an authenticated
session comes from the working of a page from a specific address)

report written by Sylvain Poirier

**Comment by vincib** [comment]
Thank you for this complete and precise report. 
The CSRF function is quite new (planned to be published on 3.3.11, which, it seems, Lautre.Net already use (...) and I'm glad you reported it that soon.
I'll first fix it by adding a few more hours in the token duration (a day or so should be fine, and it's clearly not a problem for the CSRF table in MySQL...) 

Also, I'll try to ensure, for this form (I don't think we'll need that for the others) we can keep the editor with the posted text when something goes wrong.

I'll keep you informed here.

**Comment by vincib** [comment]
Weird: The CSRF token is purged only after 1 DAY of being created. So I think the problem lies somewhere else...

Maybe the user did "back" and reused the token. As a result, I changed the bro_editor to allow an invalid token. It will spit the token error BUT allow you to continue your editing, and the next SUBMIT will work.
