### ISSUE TITLE
bug suppression de répertoire

### ISSUE THREAD

**Issue by asso-infini** [AlternC/AlternC#116]
Gros bug (à confirmer car nous n'avons pas d'instance alternc de test), qui nous abloqué toute la plate-forme :
J'ai supprimé depuis le panel un répertoire nommé install.old : ça a planté le panel, mais je me suis aperçu que ça avait rempli /var/log/alternc/bureau.log jusqu'à saturer la partition sur laquelle était le fichier de log. 
Contenu du log, on voit qu'il rajoute un / à chaque itération, jusqu'à saturation :
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old/) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old//) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old///) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old////) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old/////) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old//////) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old///////) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old////////) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old/////////) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old//////////) -
02/09/2016 13:24:15 - xx.xx.xx.xx - CALL - lelogin - bro - _delete(/var/www/alternc/l/lelogin/www/install.old///////////) -
(ad libitum)

**Comment by asso-infini** [comment]
J'ai corrigé le sujet : au début je pensais que c'était le "." qui posait problème, mais il y en avait d'autres dans le chemin complet.
Donc je sèche, je ne vois pas pourquoi cet emballement :/

**Comment by asso-infini** [comment]
Je confirme ce bug, dans le bureau.log que je trouvais anormalement énorme ce mois-ci, j'ai trouvé çà:
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store/) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store//) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store///) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store/////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store//////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store///////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store/////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store//////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store///////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store////////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store/////////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store//////////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store///////////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store////////////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store/////////////////) - 
28/10/2016 17:08:20 - xxx.xxx.xxx.xxx - CALL - le_login - bro - _delete(/var/www/alternc/l/le_login/www/le_login.infini.fr/phpBB3/store//////////////////) - 

Et ainsi de suite jusqu'au plantage, soit environ sur 48000 lignes, avec un "/" de plus à chaque ligne.

**Comment by innoticFR** [comment]
Idem de mon coté, bug qui a rempli la partition.

**Comment by innoticFR** [comment]
A priori c'est surement lié à un bug de suppression lorsqu'un élément est supprimé deux fois (par exemple si la personne s'impatiente et recharge la page).

        if (is_dir($file)) {
            $handle = opendir($file);
            while (($filename = readdir($handle)) !== false) {
                if ($filename != "." && $filename != "..") {
                        echo "1. $filename\n";
                }
            }
         }

Il n'est normalement pas possible d'atteindre la ligne `opendir()` si `isdir()` renvoie false mais comme le contenu de la fonction `is_dir()` est mis en cache (cf clearstatcache()) on peut arriver à ce bug.

Et `readdir(false)` renvoie NULL et non FALSE

**Comment by innoticFR** [comment]
This apparently was fixed in 4f3604e7177ca6c06445bd34d25a51c1aeaf751a

**Comment by vincib** [comment]
Also fixed by a safeguard in c7226c901020dd26f5544209a2b3e9114b7bc386
and the CSRF feature that 3.x.10 is bringing is preventing a *multiple reload* of POSTed data.

So anyway, this seems to be fixed in 3 different ways to me ;)
