### ISSUE TITLE
Erreur ajout domaine en eu

### ISSUE THREAD

**Issue by totom17** [AlternC/AlternC#12]
Lors de l'ajout d'un .eu Alternc retourne : 
Notice: Undefined variable: tmp in /usr/share/alternc/panel/class/m_dom.php on line 1002

**Comment by totom17** [comment]
Corrigé par Benji
Ajouter à la ligne 999 un $tmp="";
Juste avant la ligne : if ($found)

**Comment by vincib** [comment]
Fixed in eba60af8b9a538e11851b42991e80b6f402dcf7e
