### ISSUE TITLE
Change panel database tables to InnoDB

### ISSUE THREAD

**Issue by lelutin** [AlternC/AlternC#121]
It was noted in #98 that switching tables to engine innodb might help out with performance on a busy server. This is partly because of innodb's ability to do row locking instead of locking the whole table on every operation.

We should probably switch most or all tables in the panel database to use the innodb engine.

**Comment by vincib** [comment]
good idea, (and maybe recommend mariadb too ;) ) will see how we can add an engine switch in upgrades/ script + changing it in install scripts (mysql.sql)
