### ISSUE TITLE
Optionnal fixperm on alternc.install

### ISSUE THREAD

**Issue by nahuelange** [AlternC/AlternC#123]
It should be great to have an option to bypass fixperm.sh on alternc.install.
On big installs, when you change just a line in a configuration file, it take a while to deploy new confs because of fixperms execution, if you do it 3 times in a short time, it needs too much time for not any real benefit.

**Comment by skhaen** [comment]
you can already `Ctrl + c`, and press "y" to bypass it ;-)

**Comment by nahuelange** [comment]
This is not userfriendly, but ok :)
