### ISSUE TITLE
dmarc record and empty sub_domaine

### ISSUE THREAD

**Issue by nahuelange** [AlternC/AlternC#128]
AlternC seems to have a "big" issue with dmarc records and sub_domaines with empty "sub" (like http://mydomain.com).
When you add a new dmarc record (that is a TXT record with empty sub), update_domains.sh delete the apache vhost for the domain with no sub.
You need to pass the domain in web_action=UPDATE status to make it working again.

**Comment by vincib** [comment]
Duplicate of  #138

**Comment by nahuelange** [comment]
Hmm, pas sûr que ce soit un duplicat.
Ici on parle des enregistrements DNS pour dmarc, le problème de denis semble lié à la génération des vhosts.

**Comment by vincib** [comment]
Si si : #138 parle justement de la génération des vhosts ;)
