### ISSUE TITLE
[php] le répertoire de sessions n'est pas inclus dans open_basedir

### ISSUE THREAD

**Issue by denis-dordoigne** [AlternC/AlternC#129]
Certains frameworks lisent directement les fichiers de sessions, ils ont besoin pour cela de pouvoir y accéder, ce qui n'est pas possible avec la configuration poussée par défaut :
`php_admin_value open_basedir "/var/www/alternc//d/denisd/:/usr/share/php/"`

Je propose d'ajouter le session.save_path à l'open_basedir. Cela ne permettra pas de voir les sessions des autres utilisateurs, les droits sont bien positionnés par php pour n'être accessibles en lecture que par l'utilisateur :

```
  # ls -l /var/lib/php5/sess_ojn78g1chtp94lhmmob2edkc06
  -rw------- 1 fonderie fonderie 227 oct.  22 17:08 /var/lib/php5/sess_ojn78g1chtp94lhmmob2edkc06
```

**Comment by innoticFR** [comment]
Le problème risque de se situer au niveau du garbage collector. Si on autorise les sites à écrire directement dans les répertoires de session, il est dès lors possible de ne pas respecter la hiérarchie définie. Cela permet également d'outrepasser certaines restrictions mises sur la partition /var/www qu'on ne peut pas mettre sur /var/lib, par exemple "noexec", ou d'outrepasser les quotas puisqu'ils n'existent pas sur cette partition.

A priori, si certains frameworks veulent construire leurs propres fichiers de sessions sans passer par le mécanisme interne de PHP, il vaudrait mieux que l'utilisateur fixe son propre répertoire de session, par exemple dans /var/www/alternc/l/login/tmp/sessions.

**Comment by denis-dordoigne** [comment]
Je suis d'accord, j'ai ouvert un bug du côté de framework, je pense qu'on peut fermer le ticket côté alternc.
