### ISSUE TITLE
Table 'alternc.certif_alias' doesn't exist

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#13]
Après une nouvelle installation d'alternc 3.2.8 + alternc-ssl, j'ai l'erreur suivante : 

ERROR 1146 (42S02) at line 1: Table 'alternc.certif_alias' doesn't exist

**Comment by vincib** [comment]
can't reproduce, may be fixed in 3.2.11

**Comment by camlafit** [comment]
Tested on fresh install wheezy, no more pb on 3.2.11 nightly
