### ISSUE TITLE
impossible de supprimer un mail sur roundcube -> pas de corbeille

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#134]
lors de la création d'une nouvelle boite mail, le dossier "trash" n'est pas généré, ce qui empêche de pouvoir supprimer des emails

**Comment by nahuelange** [comment]
1) Checker que dans la conf dovecot il y a bien l'autocreate sur le répertoire trash
2) vérifier que le répertoire Trash est bien attribué à la "corbeille" dans la conf de roundcube

**Comment by vincib** [comment]
Fait dans c8b3d1af2a0819b05dcbc2528a622003d7c9653b
