### ISSUE TITLE
Supprimer une entrée TXT supprime la configuration apache

### ISSUE THREAD

**Issue by denis-dordoigne** [AlternC/AlternC#138]
J'ai denis.infini.fr qui est une redirection (entrée DNS A + conf apache)

J'ai créé une entrée DNS TXT pour denis.infini.fr, que j'ai supprimé ensuite

=> le fichier de configuration du vhost a été supprimé (petit bug moche), mais il est toujours inclus dans le include_alternc.conf (gros bug moche, apache ne peut plus démarrer)

```
web03 ~ # apachectl -S
apache2: Syntax error on line 267 of /etc/apache2/apache2.conf: Syntax error on line 15 of    /etc/apache2/conf.d/include_alternc.conf: Could not open configuration file /var/lib/alternc/apache-vhost/4/2014/denis.infini.fr.conf: No such file or directory
Action '-S' failed.
The Apache error log may have more information.
```

**Comment by vincib** [comment]
Ce bug est là depuis des mois, et je n'arrivais pas à le reproduire, merci @denis-dordoigne :100: 

Corrigé à l'instant.
