### ISSUE TITLE
mail.domaine.tld en https

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#140]
Ce serait bien de permettre la création de https://mail.domaine.tld voire de le créer automatiquement.

On pourrait imaginer que ça appelle un script qui lance une commande du genre letsencrypt-auto certonly --webroot -m postmaster@domaine.tld -t --agree-tos  -w /var/lib/roundcube/ -d mail.domain.tld

et qu'on aie un template spécifique pour le webmail en https avec

  SSLCertificateFile /etc/letsencrypt/live/%%mail.domaine.tld%%/cert.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/%%mail.domaine.tld%%/privkey.pem
  SSLCertificateChainFile /etc/letsencrypt/live/%%mail.domaine.tld%%/chain.pem

**Comment by vincib** [comment]
Je pense qu'on devrait intégrer ça dans le "HTTPS everywhere" à mettre (urgemment à mon avis ;) ) dans AlternC... 
Si on commence à bidouiller des patchs pour passer ceci ou cela en HTTPS :( bof...

Par contre si tu veux le faire pour un vhost particulier, c'est simple : 

- générer avec letsencrypt le cert (et mettre un auto-renew + reload apache)
- copier le vhost depuis /var/lib/alternc/apache-vhost/vhost-all.conf dans /etc/apache2/sites-enabled/mail.domaine.tld.conf 
- remplacer virtualhost :80 par :443 et  ajouter les directives sslCertificateFile + SSLEngine On
- reload apache2
- enjoy ;)
