### ISSUE TITLE
Split all packages as separate project

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#141]
It's complicated to follow a sub project in alternc.
Would be split all package as specific project, should be easier to propose patch, update on each projects.

**Comment by vincib** [comment]
Are you talking about alternc-squirrelmail, alternc-awstats and alternc-roundcube ? We merged them some years ago to lighten the burden on the developpers, 
merging the mostly identical debian/ folders and install script management in all sub-projects ... 

I'm not sure we would be willing to manage 5 different debian/ packages projects ...

**Comment by camlafit** [comment]
No shouldn't be complicate to manage different project : 
* about packaging doesn't move anymore in time, then is mainly a setup step (copy/paste)
* code base could be ligther to review code as only codebase related isprovided (easier to understand code)
* generate package is no more complicate to have one or differents repositories

I've done a sample with borg backup package. To note : as improvement fpm is used to set easier packaging part

**Comment by camlafit** [comment]
Hello

It's a TIW (thinking in progress) :) Actually is not our main goal. As alternc is not api driven or cli driven we can't propose a panel package.
Actually we work to be updated with debian (follow stable version) and finalize our ssl service.
But you can contribute in front part as we have a specific stylesheet file.
I invite you to check https://github.com/AlternC/AlternC/pull/216 to have more information about this part.

And of course we are open to talk about this evolve but mightn't in our priority.
* https://github.com/AlternC/AlternC/issues?utf8=%E2%9C%93&q=api
* https://github.com/AlternC/alternc-cli

**Comment by dannycolin** [comment]
> It's a TIW (thinking in progress) :) Actually is not our main goal. As alternc is not api driven or cli driven we can't propose a panel package.

It would be rad to have an API! But I totally understand that you need to prioritize more urgent issues ;).

> Actually we work to be updated with debian (follow stable version) and finalize our ssl service.
But you can contribute in front part as we have a specific stylesheet file.

I've already took a look at it but it is still pretty limited in term of what we can do to refresh the code of the frontend.

Anyway, I first need to install AlternC locally. Last time I tried it failed badly and the installer didn't return me any errors. I'll try to get some help from people I know here at Koumbit.

> And of course we are open to talk about this evolve but mightn't in our priority.

Great! I'll be glad to help with the frontend. I'll probably open a issue/discussion about that before the end of the week because I definitely have more questions before I can get involved. :)

**Comment by camlafit** [comment]
Hello

About installation I recommend to try http://stretch.nightly.alternc.org/ we haven't documented yet. It's again a nightly but actually we consider it as stable. Maybe some tests to finish and to be confident but looks ok to try now.

@Koumbit are great :) I think you can get a great help from them. 

And welcome, open any issues/suggestions/PR as you want. We'll try to follow and continue discussion.

**Comment by camlafit** [comment]
I close this issue as more or less done. Indeed it's a background process.
All new projects are managed in differents repositories.  We have now a travis process to generate nighlty and stable version.

**Comment by camlafit** [comment]
More information are provided in https://github.com/AlternC/AlternC/wiki/Plugin-:-Enable-travis
