### ISSUE TITLE
erreurs installation sur Jessie fraîche

### ISSUE THREAD

**Issue by ulvida** [AlternC/AlternC#142]
Faisant une installation dans sur une debian Jessie fraíchement installée, après installation d'AlternC, apache ne démarre pas. 

Il est facile d'identifier que c'est le paramètre  SSLMutex dans /etc/apache2/mods-enabled/ssl.conf, qui est issu du modèle: /etc/alternc/templates/apache2/mods-available/ssl.conf, lequel [est obsolète](https://httpd.apache.org/docs/current/upgrading.html)

**Comment by ulvida** [comment]
Comme [suggéré ici](http://stackoverflow.com/questions/13969272/apache-sslmutex-issue), j'ai essayé de remplacer: 
SSLMutex  file:${APACHE_RUN_DIR}/ssl_mutex
par: 
Mutex  file:${APACHE_RUN_DIR}/ssl_mutex

Mais j'ai encore une erreur de config apache: 
dic 16 14:38:49 laika apache2[15573]: AH00526: Syntax error on line 55 of /etc/apache2/mods-enabled/ssl.conf:
dic 16 14:38:49 laika apache2[15573]: Invalid Mutex directory in argument file:/var/run/apache2/ssl_mutex

**Comment by ulvida** [comment]
Ce premier problème s'est résolu avec un: 
`mkdir /var/run/apache2/ssl_mutex`

Mais un problème de configuration apache subsiste: 
`dic 16 14:43:41 laika apache2[15698]: The apache2 configtest failed. ... (warning).
dic 16 14:43:41 laika apache2[15698]: Output of config test was:
dic 16 14:43:41 laika apache2[15698]: AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/ports.conf:18
dic 16 14:43:41 laika apache2[15698]: AH00526: Syntax error on line 45 of /etc/apache2/conf-enabled/alternc.conf:
dic 16 14:43:41 laika apache2[15698]: Either all Options must start with + or -, or no Option may.
`

**Comment by ulvida** [comment]
Le script alternc.install donne en rouge le message suivant: 
```
*****************************************************
* The certificate file : /etc/alternc/apache.pem does not exists *
* If you want to be able to use SSL/TLS             *
* please go to https://alternc.org/wiki/SSL         *
* to get information on how to create a certificate *
* Finally relaunch alternc.install                  *
*****************************************************
```
L'URL donnée: https://alternc.org/wiki/SSL, n'est plus valide. D'ailleurs on dirait qu'il n'y a plus de wiki, du [wiki de github](https://github.com/AlternC/AlternC/wiki) on redirige vers le site alternc.com, qui n'a pas de wiki...

**Comment by vincib** [comment]
la doc SSL est là désormais : https://alternc.com/SSL
(pour info, la doc est modifiable via le wiki GitHub ou la branche alternc-doc du dépot principal ;) )
