### ISSUE TITLE
Phpmyadmin messages 

### ISSUE THREAD

**Issue by ncandelier** [AlternC/AlternC#150]
Bonjour,
En me connectant sur notre interface d'administration Globenet pour gérer nos bases de données via Phpmyadmin, le système nous retourne les messages suivants : 

Certaines fonctionnalités ayant trait aux tables reliées sont désactivées. Pour une analyse du problème, cliquez ici.
La connexion au controluser tel que défini dans votre configuration a échoué.
La version de votre bibliothèque MySQL (5.1.73) diffère de la version de votre serveur MySQL (5.5.47). Ceci peut occasionner un comportement imprévisible.

Comment contourner ce problème ?

Une autre question, j'ai besoin d'utiliser les librairies suivantes sur le serveur :  "xpdf" et "antiword" afin de mettre en place un moteur de recherche. Sont elles déjà présentes ? si non, comment les installer ?

Merci pour votre support.

Cordialement.

**Comment by vincib** [comment]
Bonjour Ncandelier, désolé du délai de cette réponse...

Ce problème de PhpMyAdmin n'a aucune conséquence sur votre capacité à utiliser ce programme : cela ne fait que bloquer certaines fonctionnalités comme la mémorisation des vues que vous préférez etc. 
rien de grave donc, vous pouvez l'ignorer.

Sinon, pour le corriger, il faut aller sur le serveur (de Globenet donc) et lancer 
`dpkg-reconfigure -plow phpmyadmin`
et configurer la base de données de fonctionnement de PhpMyAdmin lui-même.

----

Pour l'autre question, les programmes xpdf et antiword doivent être installés par Globenet si vous voulez pouvoir les utiliser. un simple
`apt install antiword xpdf`
Contactez support arobase globenet.org pour cela.
