### ISSUE TITLE
Status of AlternC

### ISSUE THREAD

**Issue by kpouget** [AlternC/AlternC#154]
Hello,

what is the current status of AlternC? as far as I can see in the website and releases, it's not actively developed anymore, right? should I consider switching to another server manager?

do you think AlternC will ever work with Php7? I forced the update of my server to this version, but cannot get AlternC interface to launch since then, and I cannot find out what's causing the problem...

thanks for that nice tool anyway :-)

Kevin

**Comment by vincib** [comment]
Hi Kpouget.
AlternC has not received much love lately, but a release is planned soon containing mostly security or bug fixes
AND a migration to PDO, which both fixes a big security bug in the mysql driver and the ability to work with PHP7.

We are using this future release of AlternC with PHP7 on 2 servers here, and it's working fine ;) 

You'll see the new release in the "release" tab of the github. 

Thanks for your patience :)
