### ISSUE TITLE
HTTP_X_FORWARDED_PROTO

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#155]
Sous Jessie, lors de la mise à jour du paquet vers 3.3.10~zznightly2017060 lors du lancement d'alternc.install

PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/alternc/panel/class/config.php on line 170

**Comment by vincib** [comment]
duplicate, fixed, closed
