### ISSUE TITLE
/etc/php5/conf.d/alternc.ini

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#156]
Sous Jessie, lors de la mise à jour du paquet vers 3.3.10~zznightly2017060 lors du lancement d'alternc.install

`ln: impossible de créer le lien symbolique « /etc/php5/conf.d/alternc.ini »: Aucun fichier ou dossier de ce type`

Mon fichier alternc.install contient

```
ln -fs /etc/alternc/alternc.ini /etc/$php/conf.d/alternc.ini || true
```
Alors qu'il faudrait ceci:

```
ln -fs /etc/alternc/alternc.ini /etc/$php/apache2/conf.d/alternc.ini || true
ln -fs /etc/alternc/alternc.ini /etc/$php/cli/conf.d/alternc.ini || true
```
C'est comme si ce commit n'était pas présent
https://github.com/AlternC/AlternC/commit/5bae6babfb2534f6c2364287775e7380eafce342

**Comment by kent1D** [comment]
Effectivement, même problème, à priori, il n'aurait pas réinstallé alternc.install
`/usr/sbin/alternc.install` est différent de `/usr/share/alternc/install/alternc.install`

**Comment by vincib** [comment]
lrwxrwxrwx 1 root root 40 juin  27 02:02 /usr/sbin/alternc.install -> ../share/alternc/install/alternc.install

l'un étant un symlink de l'autre, il n'est *pas normal* que tu n'aie pas le même fichier @kent1D ?!

Pour moi ce bug a été fermé en meme temps que le #161
