### ISSUE TITLE
paquet générés sur stable-3-3.nightly.alternc.org/ pas corrects

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#161]
Les paquets deb générés sur le dépôt (http://stable-3-3.nightly.alternc.org/ latest/)
 ne sont pas corrects, il n'incluent pas tout les commits.

2 exemples que j'ai remarqué mais il y en a peut-être d'autres

alternc_3.3.10~zznightly201706071642_all.deb

n'intègre pas ce commit
https://github.com/AlternC/AlternC/commit/5bae6babfb2534f6c2364287775e7380eafce342

alternc-mailman_3.3.10~zznightly201706071642_all.deb

n'intègre pas ce commit 
https://github.com/AlternC/alternc-mailman/commit/993fd0cdd4d687bf1910192ec6b7db687c13edad

**Comment by vincib** [comment]
en effet, ce patch pour alternc.install est pour le fichier alternc.install de WHEEZY, pas de JESSIE. (3.3.X = jessie)

Je vais faire un diff wheezy/jessie de alternc.install et autres fichiers, mais si tu remarques d'autres commit manquants, n'hésite pas à rouvrir ce ticket. Merci !
