### ISSUE TITLE
Undefined index: HTTP_X_FORWARDED_PROTO

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#162]
Sous jessie, 

/usr/lib/alternc/cron_users.sh, do_actions.php, ... renvoient ceci 

PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in /usr/share/alternc/panel/class/config.php on line 172

Mais du coup, génèrent pas mal de mails inutiles

**Comment by quenenni** [comment]
Dans le fichier config.php, ne faudrait-il pas changer le '&&' par un '||' pour la condidition du if?
```
if (!isset($_SERVER["HTTP_X_FORWARDED_PROTO"]) || $_SERVER["HTTP_X_FORWARDED_PROTO"]=="https") {
    $_SERVER["HTTPS"]="on";
}
```
Si c'est un &&, il passe à la 2ème condition uniquement si la première est vrai.
La 1ère est vrai si $_SERVER["HTTP_X_FORWARDED_PROTO"] n'existe pas, et donc la 2ème va automatiquement générer l'erreur.

Après changement, les erreurs n'apparaissent plus.

**Comment by quenenni** [comment]
Ceci dit.. 
Il est possible que l'erreur soit le ! devant la première condition et que le but de ce 'if' est de voir si cette variable existe et si elle existe, a-t'elle la valeur 'https'.
Dans ce cas, il faut mettre:
```
if (isset($_SERVER["HTTP_X_FORWARDED_PROTO"]) && $_SERVER["HTTP_X_FORWARDED_PROTO"]=="https") {
    $_SERVER["HTTPS"]="on";
}
```

Ou bien alors ne mettre que 1 & au lieu de 2 pour que les 2 conditions soient testées quelque soit le résultat de chaque condition.
Mais, dans ce cas, on continuera à  avoir les warning dans les logs puisque les 2 conditions sont mutuellement opposées..

**Comment by vincib** [comment]
duplicate, fixed at 5421c05aae8b1d8794aca515549ec95416450f23 by pull request
