### ISSUE TITLE
plusieurs admins connectés en même temps

### ISSUE THREAD

**Issue by quenenni** [AlternC/AlternC#173]
Si plusieurs personnes se connectent dans la même période avec le compte admin, ce qu'on fait chez nous car donner les droits de super-user à un compte ne lui fait pas tout voir, quand on utilise la fonction  'you may return to your account', lien en haut de la page, ça ne marche pas.
On revient non-stop à la page home du compte dans lequel on est et non le compte admin.

Pour désactiver ça.
Dans le fichier admin/adm_login.php, à la ligne 61, mettre en commentaire ce bloc if
```
/*  if ($r['lastip'] != get_remote_ip() ) { 
    $error=_("Your IP is incorrect.");
    include("index.php");
    exit();
  }*/
```

C'est bien sûr dommage de se priver de cette protection. Si y a moyen que le ticket #151 soit traité, je la remettrai avec plaisir.

**Comment by vincib** [comment]
There is another (big) issue with this IP address checking feature : 

- people behind Carrier-grade NAT https://en.wikipedia.org/wiki/Carrier-grade_NAT will likely see their public IP address change often, kicking them out of their panel
- people using dual-stack IPv4/IPv6 panel may connect to it using sometimes IPv4, sometimes IPv6 : they would be kicked too.

I propose that we just *remove* this feature altogether.

**Comment by lelutin** [comment]
👍
