### ISSUE TITLE
The certificate's owner does not match hostname 'debian.alternc.org'

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#176]
wget https://debian.alternc.org/key.txt -O - | apt-key add - 
converted 'https://debian.alternc.org/key.txt' (ANSI_X3.4-1968) -> 'https://debian.alternc.org/key.txt' (UTF-8)
--2017-07-20 17:25:50--  https://debian.alternc.org/key.txt
Resolving debian.alternc.org (debian.alternc.org)... 2001:67c:288::27, 91.194.60.27
Connecting to debian.alternc.org (debian.alternc.org)|2001:67c:288::27|:443... connected.
The certificate's owner does not match hostname 'debian.alternc.org'

**Comment by vincib** [comment]
fixed, letsencrypt, thanks !
