### ISSUE TITLE
SSLMutex is replaced by Mutex / Jessie

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#177]
In apache 2.4  SSLMutex is replaced by Mutex

https://httpd.apache.org/docs/2.4/upgrading.html

**Comment by camlafit** [comment]
To complete

Pb is at line 54 of /etc/apache2/mods-enabled/ssl.conf:

Replace SSLMutex by Mutex is not enough : 
Invalid Mutex directory in argument file:/var/run/apache2/ssl_mutex


https://httpd.apache.org/docs/2.4/mod/core.html#mutex

**Comment by camlafit** [comment]
mkdir /var/run/apache2/ssl_mutex is required

**Comment by vincib** [comment]
fixed at ea3371ae3489c254523ca7af9c87a03dc27431c4

**Comment by BoOz** [comment]
Si ca peut servir à quelqu'un j'ai du faire en plus `apt-get install alternc-ssl --reinstall`
