### ISSUE TITLE
Apache 2.4 : NameVirtualHost obsolete

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#178]
In /usr/lib/alternc/install.d/alternc-ssl , script add <IfModule mod_ssl.c>\n  NameVirtualHost *:443\n\n</IfModule> in /etc/apache2/ports.conf

Could be provoc conflict during alternc.install (apache2 can not (re)start). 
``` 
apache2AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/ports.conf:22
```

**Comment by vincib** [comment]
this is a warning, not an error, doesn't prevent apache to restart. will fix that for jessie though, give ma a minute ;)

**Comment by camlafit** [comment]
Ciao

Is noted as warning but restart was in error.  Solve it was required to prevent any problem.

Thank to solve it ;)
