### ISSUE TITLE
Alternc et Https

### ISSUE THREAD

**Issue by quenenni** [AlternC/AlternC#183]
Je me demandais où en était le projet pour intégrer let's encrypt dans AlternC.
Est-ce que je peux aider à faire avancer le schmillblick?

Pour l'instant, j'utilise un script maison pour générer le certif (avec let's encrypt) et le vhost que je met dans /etc/alternc/apache2-ssl.conf, et je vais ensuite rediriger les http vers https dans l'interface AlternC pour ce domaine.

Ca fonctionne, mais c'est pas top. Les utilisateurs ne peuvent plus faire de modifs eux-mêmes de leurs domaines (faire pointer vers un autre dossier par exemple). Ils doivent nous le demander.

On a aussi un script maison pour avoir le roundcube en https.

Après réflexion, les 2 trucs dérangeants sont cette limitation à 5 nouveaux certifs par semaine avec let's encrypt (à moins qu'ils aient changé ça à un autre nombre, mais la limitation est toujours là) et le fait qu'il n'y ai toujours pas la commande avec let's encrypt pour connaître sa situation (j'avais créé un ticket à ce sujet il y a déjà très longtemps).

Si on pouvait à tout moment connaître sa situation (vous êtes à 3 sur 5 certifs pour les 7 dernis jours par ex), ce ne serait pas dur de le proposer aux utilisateurs en expliquant la limite et qu'ils doivent revenir le faire dans x jours si on ne peut plus en créér pour l'instant.

Je pense qu'il est grans temps de s'activer à cette fonctinnalité car les navigateurs vont bientôt montrer des alertes quand les sites ne seront pas en https. 

J'ai reçu des mails de google à ce sujet:
```
Chrome will show security warnings on http://www.xxx.org

To owner of http://www.xxx.org,

Starting October 2017, Chrome (version 62) will show a “NOT SECURE” warning when users enter text in a form on an HTTP page, and for all HTTP pages in Incognito mode.

The following URLs on your site include text input fields (such as < input type="text" > or < input type="email" >) that will trigger the new Chrome warning. Review these examples to see where these warnings will appear, so that you can take action to help protect users’ data. This list is not exhaustive. 

http://www.xxx.org/subscribe/intern.php 

The new warning is part of a long term plan to mark all pages served over HTTP as “not secure”.
Here’s how to fix this problem:

Migrate to HTTPS
...
```

**Comment by vincib** [comment]
- je n'ai **absolument pas** mesuré une limite de 5 certs/semaine sur letsencrypt, en ayant généré une quinzaine ou une vingtaine sur le même serveur dans la même heure ces derniers mois. Je pense qu'on peut foncer

- oui, il faut que l'on voit comment on intègre letsencrypt, je suis même pour que ce soit automatique et systèmatique (que tout vhost http soit aussi accessible en https, quitte à proposer "rediriger http vers https" ou l'inverse etc.)

**Comment by vincib** [comment]
à Octopuce, on a déjà une façon de faire ça : 
- installation de nginx (de dotdeb sur Jessie pour avoir HTTP/2) 
- configuration automatique via un script cronifié pour que tout Vhost se voit généré un cert letsencrypt et un vhost nginx proxifiant vers le http + headers "X-Forwarded-For: <ip>" et "X-Forwarded-Proto: https"
- le client peut rediriger de force http vers https avec un .htaccess comme suit : 

```
# FORCED HTTPS :
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
```

Cette implémentation peut faire l'objet d'un package .deb assez simple que je peux vous passer.

**Comment by quenenni** [comment]
> * je n'ai absolument pas mesuré une limite de 5 certs/semaine sur letsencrypt, en ayant généré une quinzaine ou une vingtaine sur le même serveur dans la même heure ces derniers mois. Je pense qu'on peut foncer

Excellent.. Je ne savais pas qu'il avait retiré cette limitation. 
Ca change tout alors.. Dans mes réflexions sur le sujet, j'étais toujours hyper embêter par ce truc.

> * oui, il faut que l'on voit comment on intègre letsencrypt, je suis même pour que ce soit automatique et systèmatique (que tout vhost http soit aussi accessible en https, quitte à proposer "rediriger http vers https" ou l'inverse etc.)

Je suis totalement pour ça aussi.
Avoir l'option "Rediriger Http vers Https", cochée par défaut, est très bien.

.. Juste une idée sur le processus..
La génération du certif peut se faire 1 par domaine avec tous les sous-domaine en "alt name".
A chaque fois qu'on ajoute ou efface un (sous-)domaine, ça prévient le cron de refaire le certif.
Le cron récupère le domaine et tous les sous-domaine et génère le certif.
Ce sera donc le même certif pour tous les services (sites web / roundcube / ..). Nom de fichier de certif facilement retrouvable en connaissant le nom de domaine principal (ex: je cherche le certif pour tralala.xxx.org -> le nom de domaine est xxx.org -> le chemin du certif est donc /ec/letsencrypt/live/xxx.org/..)
Le cron va ensuite refaire le .htaccess (ou modifier le vhost) pour faire la redirection, il est facile d'ajouter des ligne dans ce .htaccess pour mettre des sous-domaines où on ne voudrait pas la redirection vers https.

Un truc embêtant que je vois avec le .htaccess, c'est que les cms placent déjà leur .htaccess. Cela implique d'aller chipoter dans ce fichier et cela risque d'amener des petits problèmes plus tard (update du cms / utilisateurs qui le renomme pour faire des tests ou replace celui d'origine pour voir si ça règle son problème / ..)

Une autre chose a faire attention.
Quand tu crées un certif, tu lui donnes le chemin de la racine du site.
Si qq'un va editer le nom de domaine pour le faire pointer vers un autre dossier, il faut mettre à jour le fichier de config dans /etc/letsencrypt/renewal/xxx.org)
Je ne sais pas si on peut faire ça directement avec la commande lets'encrypt ou bien s'il faut aller changer soi-même dans le fichier de config (ce que j'ai toujours fait).

**Comment by camlafit** [comment]
Bonjour

Se reporter au projet [alternc-certbot](https://github.com/alternc/alternc-certbot) 

Pour le moment le panel est automatiquement géré , le apache.pem est créé et maintenu à jour.
Pour tous les domaines hébergé, si certbot peut valider, alors le certificat est ajouté au panel.

Aux utilisateurs ensuite d'utiliser ou non le certificat

**Comment by kent1D** [comment]
Hmmm chez moi cela ne semble pas fonctionner. Fonctionne juste pour le panel.

Je ne vois pas d'endroit pour utiliser letsencrypt dans l'interface.

**Comment by camlafit** [comment]
Ne pas oublier d'activier les quota pour les ssl. Autrement il n'apparaissent pas.
De plus cf la réponse complémentaire sur l'autre fil : https://github.com/AlternC/AlternC/issues/47#issuecomment-326730398

Le plus simple aussi est de continuer sur le projet pour faciliter le suivi :) La documentation est encore imparfaite.

**Comment by camlafit** [comment]
Bonjour

La version 0.0.5 dans le dépôt stable devrait maintenant faire le travail attendu (panel et domaines hébergés). Elle est la première version considérée comme fonctionnelle.

**Comment by kent1D** [comment]
Tu peux checker le ticket que je viens de faire?

**Comment by paulcmal** [comment]
Perso j'utilise une configuration nginx générique pour tous les vhosts sur le port 80 :
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location /.well-known/acme-challenge {
                root /var/www/$host/public;
        }

        location / {
                return 301 https://$host$request_uri;
        }
}
```

Ça ne laisse passer que les requêtes ACME (type letsencrypt) en HTTP. Normalement les directives `root` et `index` ne servent à rien mais je préfère les laisser pour qu'en cas de mauvaise configuration dans la suite on arrive bien dans un dossier où il n'y a rien de dangereux. Ici du coup on présume que le site *truc.bidule.net* est servi depuis `/var/www/truc.bidule.net/public`. Voir [un exemple](https://git.hackab.org/Hackab/scripts/src/branch/master/root/web.sh) de script qui fonctionne comme ça.
