### ISSUE TITLE
Nouvelles clefs sécurisée à générer pour signer les paquets

### ISSUE THREAD

**Issue by GanGuoLang** [AlternC/AlternC#191]
Bonjour,

il faudrait générer de nouvelles clefs pour signer les paquets, parce que actuellement, c'est une clef RSA 1024 qui date de 2006 et qui est rejetée par apt.

Cela bloque l'installation de Alternc sur Debian Stable, et ça ne fait pas très sérieux.

Merci

**Comment by vincib** [comment]
The key has been changed to a 4096 RSA key, both in the repository and the doc. Thanks for your patience :)
