### ISSUE TITLE
Problème de droits suite à décompression

### ISSUE THREAD

**Issue by klorydryk** [AlternC/AlternC#20]
J’ai uploadé avec FileZilla une archive tar.gz (un owncloud), l'ai dé-taré sur mon compte avec la commande "extraire" de l'interface AlternC, et lorsqu’il s’est agi de modifier un de ces fichiers via l’éditeur de texte d’AlternC, il m’a été opposé un refus (bandeau rouge « droits d’accès insuffisants »).

**Comment by vincib** [comment]
Je n'ai réussi à reproduire ce bug qu'en décompressant un .TAR.GZ dont les fichiers ne sont pas accessible en ÉCRITURE à l'utilisateur par défaut. 

Dans ce cas il faut cocher le fichier ,choisir "permissions" dans le gestionnaire de fichier, et ajouter sa permission en écriture. 

Proposition de modification d'interface : 
- quand on clique sur un fichier, si ce dernier n'est pas accessible en écriture, prévenir l'utilisateur, mais permettre ses modifications tout de même (et renlever le droit d'écriture une fois écrit)
- dans le gestionnaire de fichier, si cela n'est pas coûteux, signaler les fichiers en lecture seule

**Comment by vincib** [comment]
résolu en affichant les droits dans le browser
