### ISSUE TITLE
La configuration TLS de dovecot est forcée dans 96_ssl.conf

### ISSUE THREAD

**Issue by lelutin** [AlternC/AlternC#204]
Salut,

J'ai un bug avec la manière d'alternc de générer la configuration de dovecot pour le TLS. Le script alternc.install force le contenu du fichier 96_ssl.conf dès qu'un certificat existe dans /etc/alternc/apache.pem.

voir: https://github.com/AlternC/AlternC/blob/stable-3.1/wheezy/alternc.install.diff#L19

ça rend ça complexe d'utiliser un certificat Let's Encrypt pour imap/pop3 puisque celui-ci ne génère pas un fichier qui amalgame certificat, chain et clef et donc il faut regénérer ce fichier par nous-même dans un hook de LE.

ça rend aussi la tâche impossible quand on veut utiliser un certificat différent pour pop3/imap, par exemple si on a séparé ce service sur une autre machine que le paneau de contrôle.

pour le cas de postfix, la configuration du certificat TLS est faite via le template /etc/alternc/templates/postfix/main.cf -- il existe déjà un template pour dovecot dans ce répertoire alors ça serait bien qu'on utilise ça à la place et qu'on laisse tomber le fichier 96_ssl.conf

**Comment by camlafit** [comment]
Hello

On n'a pas de /etc/alternc/templates/postfix/main.cf pas sur de comprendre ce point

**Comment by sebas891** [comment]
Je vais essayer de clarifier ici. Par défaut AlternC met en dur dans la conf de dovecot le cert ssl par défaut.  Le code est ici.

https://github.com/AlternC/AlternC/blob/b7be237b6d66a1ecb38460cf721b6af6ce12fcd4/install/alternc.install#L346

La possibilité est d'aller créer un fichier directement là /etc/dovecot/conf.d/99_ssl.conf qui overwrite la définition précédente de 96_ssl.conf.

Il serait plus pratique et cohérent avec la méthode AlternC d'utiliser un template pour la définition du cert ssl pour dovecot.  96_ssl.conf devrait être un template à mon avis.

Ça va déja bien mieux coté postfix pour la définition du cert ssl, on fait ça ici, dans la section des templates. (Bon, c'est pas un template, c'est un fichier avec une série de paramètres passés à postconf)
https://github.com/AlternC/AlternC/blob/b7be237b6d66a1ecb38460cf721b6af6ce12fcd4/etc/alternc/templates/alternc/postfix/postfix.cf#L25

A+

**Comment by sebas891** [comment]
Je note que dans la branche master, on a le changement qu'on voulait.

https://github.com/AlternC/AlternC/blob/db916ace66039f8125417fc9b2b18c1d14fb9afd/install/alternc.install#L348

Il y a maintenant un template ici: /etc/alternc/templates/dovecot/conf.d/96_ssl.conf

https://github.com/AlternC/AlternC/blob/db916ace66039f8125417fc9b2b18c1d14fb9afd/etc/alternc/templates/dovecot/conf.d/96_ssl.conf#L1

@lelutin je crois qu'on peut fermer ce ticket ici, on ouvrira un nouveau ticket si jamais il y a des bugs avec la nouvelle implantation.

**Comment by lelutin** [comment]
@sebas891 super!

**Comment by kienanstewart** [comment]
Le fichier de conf a été inclus dans /etc/alternc, mais pas déployé. Voir PR #280
