### ISSUE TITLE
missing items from installation and ssl documentation

### ISSUE THREAD

**Issue by soul9** [AlternC/AlternC#209]
To install alternc-roundcube on jessie one needs to enable debian backports, which is not specified anywhere in the https://alternc.com/Install-en document.

To install the ssl certificate with letsencrypt, the https://alternc.com/SSL-fr page is missing 4/5th of the apache configuration, the correct configuration is:
```
Alias /.well-known/acme-challenge /var/www/letsencrypt/.well-known/acme-challenge
<Directory /var/www/letsencrypt/.well-known/acme-challenge>
  Order allow,deny
  Allow from all
</Directory>
```

**Comment by soul9** [comment]
the ssl documentation also states "Lors du lancement de alternc.install, le script regarde si des fichiers /etc/alternc/fullchain.pem et /etc/alternc/privkey.pem sont présents", which is false, the actual way to enable the generated certificate is to
```
cat /etc/letsencrypt/live/alternc.roxor.me/cert.pem /etc/letsencrypt/live/alternc.roxor.me/privkey.pem > /etc/alternc/apache.pem
```

**Comment by camlafit** [comment]
hello

to use let's encrypt we recommend to use alternc-certbot plugin. 
To note is actually compatible with nightly version , some bugfixes requires latest alternc version.

https://alternc.com/SSL-fr  looks outdated. We'll update it

**Comment by soul9** [comment]
Thank you, I might install the nightly soon, then. Other than that, then, I think I can close this ticket. I think the backports thing is not that important since it's just for jessie, and just for the alternc-roundcube support.
