### ISSUE TITLE
En stretch, Alternc-ssl 3.3.11 plante à l'installation (undefined function mysql_connect())

### ISSUE THREAD

**Issue by sebas891** [AlternC/AlternC#222]
<pre>
/usr/lib/alternc/quota_init ssl 0
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in 
 /usr/lib/alternc/quota_init:26
Stack trace:
#0 {main}
  thrown in /usr/lib/alternc/quota_init on line 26
</pre>

mysql_connect n'est plus présent dans php7.0
http://php.net/manual/en/function.mysql-connect.php

Dans le debian/changelog pour 3.1.11, il y a déja eu des changements pour utiliser PDO à place de mysql_*, il semble avoir eu des oublis.

On retrouve des mysql_connect ici et à d'autres endroits encore.

src/quota_init:26:if (!mysql_connect($L_MYSQL_HOST,$L_MYSQL_LOGIN,$L_MYSQL_PWD)) {
src/alternc_fix_opendkim.php:55:$res=mysql_connect($mhost,$muser,$mpass);
src/quota_delete:22:if (!mysql_connect($L_MYSQL_HOST,$L_MYSQL_LOGIN,$L_MYSQL_PWD)) {

voilà, ça prendrait des modifications au code pour eliminer les mysql_connect

**Comment by sebas891** [comment]
@GuillaumeFromage  a fait ça sur le coin de la table, ça fonctionne, mais je doute que ça suivre les standards dans alternc pour la gestion des connexions mysql etc...

<pre>
$ diff  ../AlternC/src/quota_init quota_init 
26c26
< if (!mysql_connect($L_MYSQL_HOST,$L_MYSQL_LOGIN,$L_MYSQL_PWD)) {
---
> if (!($mysqli = new mysqli($L_MYSQL_HOST,$L_MYSQL_LOGIN,$L_MYSQL_PWD, $L_MYSQL_DATABASE))) {
31,37c31,32
< if (!mysql_select_db($L_MYSQL_DATABASE)) {
< 	echo "Cannot connect to Mysql database $L_MYSQL_DATABASE !\n";
< 	return 1;
< }
< 
< $r=mysql_query("DELETE FROM defquotas WHERE quota='$name';");
< if (mysql_errno()) {
---
> $r=$mysqli->query("DELETE FROM defquotas WHERE quota='$name';");
> if ($mysqli->errno) {
42,43c37,38
< $r=mysql_query("INSERT INTO defquotas (quota,value) VALUES ('$name','$quota');");
< if (mysql_errno()) {
---
> $r=$mysqli->query("INSERT INTO defquotas (quota,value) VALUES ('$name','$quota');");
> if ($mysqli->errno) {
48,49c43,44
< $r=mysql_query("SELECT uid FROM membres;");
< if (mysql_errno()) {
---
> $r=$mysqli->query("SELECT uid FROM membres;");
> if ($mysqli->errno) {
53,56c48,51
< while ($c=mysql_fetch_array($r)) {
< 	$s=mysql_query("SELECT name FROM quotas WHERE uid='$c[uid]' AND name='$name';");
< 	if (!mysql_num_rows($s)) {
< 		mysql_query("INSERT INTO quotas (uid,name,total) VALUES ('$c[uid]','$name','$quota') on DUPLICATE KEY UPDATE total=$quota;");
---
> while ($c=$r->fetch_assoc()) {
> 	$s=$mysqli->query("SELECT name FROM quotas WHERE uid='$c[uid]' AND name='$name';");
> 	if (!$s->num_rows) {
> 		$mysqli->query("INSERT INTO quotas (uid,name,total) VALUES ('$c[uid]','$name','$quota') on DUPLICATE KEY UPDATE total=$quota;");

</pre>

**Comment by soul9** [comment]
j'ai un fix rapide dans https://github.com/AlternC/AlternC/pull/199/files#diff-79d4834f2886cb7fbc413394edeb888f

**Comment by sebas891** [comment]
@soul9 merci!

Je vois que plus spécifiquement c'est ici:
https://github.com/soul9/AlternC/blob/470ed9cd1535461c7a809ce6c8d55919b76f14a0/stretch/quota_init.diff
A+

**Comment by demonicpancake** [comment]
Ça semble fonctionner, mais on a maintenant ça dans le output:

`Paramétrage de alternc-ssl (3.3.11) ...                                                                                                 
PHP Warning:  mysqli_query() expects at least 2 parameters, 1 given in /usr/lib/alternc/quota_init on line 58                           
PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /usr/lib/alternc/quota_init on line 59           
PHP Warning:  mysqli_query() expects at least 2 parameters, 1 given in /usr/lib/alternc/quota_init on line 60                           
PHP Warning:  mysqli_query() expects at least 2 parameters, 1 given in /usr/lib/alternc/quota_init on line 58                           
PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /usr/lib/alternc/quota_init on line 59           
PHP Warning:  mysqli_query() expects at least 2 parameters, 1 given in /usr/lib/alternc/quota_init on line 60                           
PHP Warning:  mysqli_query() expects at least 2 parameters, 1 given in /usr/lib/alternc/quota_init on line 58                           
PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /usr/lib/alternc/quota_init on line 59           
PHP Warning:  mysqli_query() expects at least 2 parameters, 1 given in /usr/lib/alternc/quota_init on line 60`

**Comment by kienanstewart** [comment]
Fixed the warnings and applied @soul9's changes in the PR #239
