### ISSUE TITLE
Alternc-SSL: "key missmatch" 

### ISSUE THREAD

**Issue by 0xTHMS** [AlternC/AlternC#223]
Bonjour,

AlternC:  3.2.11~zznightly201802130201
Lors de l'utilisation d'alternC SSL, celui-ci propose la création CSR et de la clé associée.
Or, si une personne utilise l'outil de génération CSR proposé par beaucoup de vendeurs de SSL, ou génère lui même son CSR et sa clé, AlternC ne remplace pas la clé par celle utilisée.
Ainsi, au prochain redémarrage Apache, celui-ci refuse de se lancer et l'erreur: key values missmatch apparaît.

Le même problême est présent lorqu'on coche "VHOST SSL" pour un sous-domaine dont le CSR et la clé n'ont pas été générée: AlternC les créé automatiquement mais il est impossible d'afficher quelque part le CSR. 
Cela force donc à créer son propre CSR et clé, qui seront forcément différents de ceux sur le serveur.

**Comment by camlafit** [comment]
Related to #262

**Comment by camlafit** [comment]
Hello

Je ferme le ticket depuis c'est la 3.5 qui est la version de référenc et alternc-ssl est une fonctionnalité native.
