### ISSUE TITLE
[install jessie] erreur quota

### ISSUE THREAD

**Issue by nahuelange** [AlternC/AlternC#23]
Je fais quelques bug report pour l'adaptation à jessie:

À l'install sur jessie, il y a une erreur avec l'appel à quota 
```
/var/lib/dpkg/info/alternc.config: ligne 281: quota : commande introuvable
```

**Comment by skhaen** [comment]
tu as testé avec la 3.2.9 ou avec le dépôt nightly pour jessie ? 
https://github.com/AlternC/AlternC/wiki/nightly-en

**Comment by nahuelange** [comment]
Non, on verra à la prochaine màj.

**Comment by skhaen** [comment]
tu as testé avec la version pour jessie ou pas ?

**Comment by nahuelange** [comment]
Désolé, j'ai pas du répondre au bon ticket.
La machine où ça s'est produit c'était sur l'install de la version nightly pour jessie.

**Comment by innoticFR** [comment]
According to the debian/control, AlternC **recommends** the "quota" package but /usr/bin/quota is used by alternc.config and should be in the "Depnds" section.

I moved the quota package in the correct section.
