### ISSUE TITLE
Roll wheezy, jessie, and stretch patches into source tree

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#230]
It would simplify development to roll the existing patch sets for wheezy, jessie, and stretch into the source tree to build for stable by default.

The default build is for oldoldoldstable... a bit funky. I think that should builds be needed for wheezy/jessie that the patch folders apply reverse patches where necessary.

**Comment by kienanstewart** [comment]
https://github.com/AlternC/AlternC/pull/231

**Comment by camlafit** [comment]
no more required to be opened
Change are done on git branches
