### ISSUE TITLE
[Stretch] Dépendance sur apache2

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#232]
Il manque la dépendance sur apache2 qui provoque des erreurs quand on lance alternc.install 

/usr/sbin/alternc.install: ligne 295: a2enmod : commande introuvable
/usr/sbin/alternc.install: ligne 306: a2enmod : commande introuvable
/usr/sbin/alternc.install: ligne 310: a2enmod : commande introuvable

....

/usr/sbin/alternc.install: ligne 443: a2disconf : commande introuvable

**Comment by sebas891** [comment]
Ici aussi, ça prendrait plus de détails sur la version Alternc installé à mon avis. Après plusieurs installation de d'alternc 3.3.11 dans stretch, ce problème n'a pas été constaté de mon coté.

**Comment by ddeenniiss** [comment]
J'ai eu ça sur une install Stretch avec la version 3.3.10.

De ce que je vois a2enmod et a2disconf sont installés avec apache2 uniquement qui n'est pas présent comme dépendance du paquet

**Comment by ddeenniiss** [comment]
Pas eu en version 3.5.0~rc1+0~20190412204409.39~1
