### ISSUE TITLE
[stretch] opendkim fichier /etc/default/opendkim pas pris en compte ?

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#233]
Erreur lors du script alternc.install. De ce que je comprends /etc/default/opendkim n'est pas pris en compte.

Du coup, j'ai rajouté ceci dans /etc/opendkim.conf

**UserID                  opendkim:opendkim
Socket                  inet:8891@localhost
PidFile                 /var/run/opendkim/opendkim.pid**

Job for opendkim.service failed because the control process exited with error code.
See "systemctl status opendkim.service" and "journalctl -xe" for details.
invoke-rc.d: initscript opendkim, action "start" failed.
● opendkim.service - OpenDKIM DomainKeys Identified Mail (DKIM) Milter
   Loaded: loaded (/lib/systemd/system/opendkim.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2018-04-17 08:02:08 UTC; 6ms ago
     Docs: man:opendkim(8):q
           man:opendkim.conf(5)
           man:opendkim-genkey(8)
           man:opendkim-genzone(8)
           man:opendkim-testadsp(8)
           man:opendkim-testkey
           http://www.opendkim.org/docs.html
  Process: 25156 ExecStart=/usr/sbin/opendkim -x /etc/opendkim.conf (code=exited, status=78)
 Main PID: 32756 (code=exited, status=0/SUCCESS)

avril 17 08:02:08 ns314594 systemd[1]: opendkim.service: Unit entered failed state.
avril 17 08:02:08 ns314594 systemd[1]: opendkim.service: Failed with result 'exit-code'.

**Comment by sebas891** [comment]
Allo,
Ici, c'est pas un bug d'alternc, mais de opendkim dans stretch. Je ne trouve pas bug upstream chez debian mais une discussion à propos du problème:
https://unix.stackexchange.com/questions/375152/configuring-debians-opendkim-packages-init-script-parameters-with-both-init-d

Voici la solution que j'ai d'utilisé à plusieurs reprises lors de la mise à jour à Stretch.
```
/lib/opendkim/opendkim.service.generate
systemctl daemon-reload
service opendkim restart
```
ça vient d'ici: https://serverfault.com/questions/847435/cant-change-opendkim-socket-in-debian-stretch-in-etc-default-opendkim

Opendkim dans stretch pas très en forme... J'ai aussi eu le bug suivant:
https://wiki.koumbit.net/OpenDkimMaintenance#key_data_is_not_secure

J'espère que ça pourra t'aider.

**Comment by sebas891** [comment]
Il y a un fix ici #256 ça reste à tester.

**Comment by albancrommer** [comment]
Après investigation, il semble -sauf erreur de ma part- que ce soit lié à la configuration de systemd qui ne semble pas prévue de base dans alternc qui utilise sysvinit-core comme init 

Donc #256 a sans doute juste mais va casser les installations non-systemd

**Comment by ddeenniiss** [comment]
En tout cas sous stretch, plus de soucis.
