### ISSUE TITLE
[stretch] Fichiers de conf dovecot pas copiés

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#234]
Alternc.install ne copie pas les fichiers dovecot au bon endroit:

tar: etc/dovecot/alternc-sql.conf : stat impossible: Aucun fichier ou dossier de ce type
tar: etc/dovecot/alternc-dict-quota.conf : stat impossible: Aucun fichier ou dossier de ce type
tar: etc/dovecot/conf.d/95_alternc.conf : stat impossible: Aucun fichier ou dossier de ce type
tar: Arrêt avec code d'échec à cause des erreurs précédentes
...
chgrp: impossible d'accéder à '/etc/dovecot/alternc-sql.conf': Aucun fichier ou dossier de ce type
chmod: impossible d'accéder à '/etc/dovecot/alternc-sql.conf': Aucun fichier ou dossier de ce type

**Comment by sebas891** [comment]
Peut-être donner plus de détails sur les circonstances du problème soulevé ici.

Je viens de faire l'installation des packages 3.3.11 dans une machine virtuelle en stretch et les fichiers de dovecot mentionnés sont bien présent.

**Comment by ddeenniiss** [comment]
install d'une 3.3.10 sur une stretch

**Comment by camlafit** [comment]
Normalement corrigé avec la 3.5.x
L'alternc.install a été revu et corrigé
