### ISSUE TITLE
L'installation d'AlternC échoue quand le mot de passe de la base de données contient un '&'

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#247]
Le '&' dans un mot de pass est remplacé quand c'est evalué avec sed avec le valeur d'un match. J'imagine qu'il est également possible que les autres charactères spécial de sed pourraient causer des problèmes semblables. Faudrait assurer que les mots de passes soient éscapés dans alternc.install.

**Comment by kienanstewart** [comment]
PR #253

**Comment by hubide** [comment]
Il semble y avoir un problème de merge. 

Le commit 5a4f9240888e35a591878a304940079edb7e6cb9 devrait modifier des changements du commit 4c180272ed80ab21bb25f2c3a34bd6541b724075, mais on ne voit pas ça dans le fichier install/alternc.install

**Comment by camlafit** [comment]
Hello

Thanks a lot , path is applied
