### ISSUE TITLE
Change patch management strategy

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#251]
This is somewhat related to #230, but I want to open a discussion about how the development is handled for supporting different debian versions.

It's very difficult and error prone to maintain the patch scripts and diffs they apply. It leads to easy errors and omissions (eg. 3.x.11 is released in wheezy), but the jessie patchs don't carry that changelog modification forward. Furthermore it makes building and developing for different versions tedious: currently one must checkout stable-3.1, run ./wheezy/patch.sh, run ./jessie/patch.sh and _then_ make sure not to accidentally commit any of the myriad of changed files.

I propose removing the patch scripts and folders, making the master (or stable-3.1) the default for targeting Debian unstable and where contributions should be made by default. As required, branches can be made to support older version (eg. 3.x-jessie or 3.x-stretch).

I've seen some non-native debian packages use release numbering like X.Y.Z+debN in changelogs to clearly denote which version of Debian a package is meant to target. I'm not sure if that is useful here to help managed releases.

I'd love to hear your thoughts and suggestions.

Thanks,
Kienan

**Comment by vincib** [comment]
we talked about that during latest camp a few months ago, and decided to start the following branch behavior starting from jessie : 
- a "master" branch will be the one used to release package for the latest debian release we support.
- a "dist-<codename>" branch will be created for each former debian version we will support, that will cherry pick patches from master to maintain it.
I'll do that today once azerttyui will have merged alternc-ssl.
