### ISSUE TITLE
update_domains.sh laisse vhosts_all.conf vide quand VHOST_DIR est un lien symbolique

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#257]
On a eu un bug avec update_domains où ça a l'air de ne pas lire et ajouter les fichiers vhost à vhosts_all.conf.

Éventuellement on a trouvé que sur notre système il fallait mettre un '$VHOST_DIR/' (avec le '/') pour le faire marcher. Notre système est un peu unique parce que /var/lib/alternc/apache-vhost est un lien symbolique plutôt qu'un dossier (pour pouvoir le monté sur un système de fichier partargé).

Je fera un pull request pour cette changement, vue que ça ne devriat rien brisé pour les cas où $VHOST_DIR démure un dossier normal.

**Comment by lelutin** [comment]
ceci a été mergé dans stable-3.1 déjà par la poule request #258
