### ISSUE TITLE
Backport alternc-ssl in alternc

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#262]
As ssl service is now mainly use by default, we must integrate ssl support on alternc

Our plan : 
* backport alternc-ssl in alternc
* stop alternc-ssl support
* alternc should provide generic ABI to manage certificate (yet mainly in alternc-ssl)
* certificates could be managed by differents providers (as ACME/let's encrypt, ...)
* alternc provide by default two provider : 
** snake oil  (autosigned to enable minimalist ssl support)
** manual  (user can add a certificate mainly by altenrc-ssl backport)

**Comment by vincib** [comment]
I close this one => it's mostly done in 3.5.0~rc1, to be tester though. 

Thanks everyone who participate ! <3
