### ISSUE TITLE
Mise à jour vers  3.5.0~zznightly20180622

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#264]
installing AlternC schema in alternc...
ERROR 1728 (HY000) at line 494: Cannot load from mysql.proc. The table is probably corrupted
Error loading database schema, continuing...

Stretch, Mise à jour de 3.3.11~zznightly2018062 vers 3.5.0~zznightly20180622

**Comment by camlafit** [comment]
As was an unofficial nigthly, migration script was not yet ready.
We can't confirm at this step.

Better to reopen when a rc will provided

**Comment by ddeenniiss** [comment]
Idem sous 3.5.0~rc1
