### ISSUE TITLE
client denied by server configuration: /usr/share/alternc/panel/admin/

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#265]
Sur une stretch en mise à jour vers le paquet 3.5.0~zznightly20180622 l'accès au bureau est impossible:

`client denied by server configuration: /usr/share/alternc/panel/admin/

Dans /etc/apache2/conf-enabled/alternc.conf, je suis obligé de mettre`

```
<Directory /usr/share/alternc/panel/admin/>
  Order allow,deny
  Allow from all
```

A la place de 
```
<Directory /usr/share/alternc/panel/admin/>
 Require all granted
```

**Comment by sebas891** [comment]
Je confirme le même problème, je prépare un PR pour régler le problème.

**Comment by sebas891** [comment]
J'ai lu vite un peu. Dans Stretch et Jessie c'est apache2.4 par défaut, donc on ne veut pas de config Order allow,deny mais bien dans le style Require all granted

J'ai un PR #266 qui règle le problème d'accès.

**Comment by sebas891** [comment]
Le merge a été fait, si tu peux tester stp et fermer le ticket ici.

**Comment by vincib** [comment]
good for me (tested in the train :) )
