### ISSUE TITLE
Manque des "domaines_type" pour le support https partout

### ISSUE THREAD

**Issue by sebas891** [AlternC/AlternC#277]
"/etc/alternc/templates/apache2/vhost.conf" a été rennomé par vhost-http.conf selon les derniers  commits 

vhost-http vhost-https et vhost-both ne sont pas définis dans la table domaines_type.

https://github.com/AlternC/AlternC/blob/db916ace66039f8125417fc9b2b18c1d14fb9afd/install/mysql.sql#L482

On note qu'il y a bien des templates de vhost pour la configuration d'apache dans /etc/alternc/templates/apache2/ voir https://github.com/AlternC/AlternC/tree/master/etc/alternc/templates/apache2

vhost-both.conf  vhost-http.conf  vhost-https.conf

mais vhost.conf n'est plus présent. 

Conséquence, la run de "update_domaine" ne génère plus de vhost dans le fichier /var/lib/alternc/apache-vhost/vhosts_all.conf

Est-ce possible qu'il manque du code pour faire les vérifications sur les templates de disponible? ici /usr/lib/alternc/functions_hosting.sh

**Comment by kienanstewart** [comment]
Je ne pense pas que les entrées manquantes dans domaines_type sont la cause de la non-génération des vhosts.

Les nouveaux domaines semblent toujours être créer avec le type "vhost" (quand on choisse locally hosted). Vue que le template manque, rien arrive.

Pour un fix quick, je ferai un lien symbolique de vhost.conf vers vhost-http.conf dans les templates pour assurer que la fonctionalité de base continue a marcher.

**Comment by sebas891** [comment]
Je suis a voir qu'il y a un système de hook de défini ici

https://github.com/AlternC/AlternC/blob/db916ace66039f8125417fc9b2b18c1d14fb9afd/src/functions_hosting.sh#L6

ça pointe vers ce répertoire
/etc/alternc/functions_hosting

https://github.com/AlternC/AlternC/blob/db916ace66039f8125417fc9b2b18c1d14fb9afd/src/functions_hosting.sh#L22

Il y a un série de liens symboliques qui pointe vers le fichier hosting_vhost-ssl.sh qui n'existe pas...

Mais ce fichier a été bougé voir commit 8232c1a31803f8e3f033c4951571ddf4d4bcd764

**Comment by kienanstewart** [comment]
Il se peut qu'il y a un script spécial pour vhost qui manque, mais après avoir regardé j'ai décidé de pas essayer de re-créer ça.

Je viens de faire plusieurs petites modifications pour mettre la fonctionalité plus en forme:

* lors d'une installation fraiche, has_https_option est vrai par défaut pour les sous-domaines de type 'vhost'
* entre Sebas et moi, on a ajouté les types "overloaded" de vhost à table domaines_type, mais les overloads sont cachés de l'interface. ça permet a un check dans m_ssl::updateDomain de procèder pour des vhosts de type 'vhost-https', etc.
* dans updates_domaines, pour le enable/disable/create/update le type de vhost est modifié par le valeur de la colonne https si c'est rempli (donc vhost have https = 'both' devient 'vhost-both') et donc le bon template est choisi

Il y a pt-être quelque'chose à investiguer plus, mais une des problèmes qu'on a eu est parce que les scripts de update de la B-D n'ont pas roulé.

J'ai également nettoyé la selection par défaut de type de SSL dans dom_edit; il avait des cas où plusieurs types étaient "selected" en même temps donc la formulaire n'avait pas un défaut qui matchaient ce qui existaient déjà dans la base de données.

Tout le travail est dans https://github.com/Koumbit/AlternC/tree/277-no_default_vhost_template

Pour les maintainers: Est-ce que la solution en tête pour vhost c'était d'avoir un script spécial pour le templating des vhost? Si ça existe à qlq'part c'est pas dans la branche présentement.

**Comment by camlafit** [comment]
Hello

À propose de cette issue, je la passe en wontfix car nous allons supprimer ce comportement.
Dans le cadre de la 3.5 finale, on aura toujours les 2 vhosts de déclarés. 

Maintenant il n'est plus pertinent de ne proposer que du http. De plus la gestion des certificats est intégré nativement dans le core plus module pour avoir divers provider.

Selon la roadmap soit ce serat intégré à parrtir de la 3.5rc4 ou bien dans une 3.6 si le chantier demande trop de travail

**Comment by camlafit** [comment]
Hello

On a trop divergé pour retomber juste :/
Je propose donc : 
* fermeture du ticket présent
* rattrapage des fusions en retard
* reprendre la question quand nous aurons une branche de référence stable 

Il faut reprendre la question plus globalement avec probablement l’arrêt du http simple et ou ne proposer que du both par défaut.
Il y a aussi une question subsidiaire sur la gestion de payload pour donner des options au vhost (le ssl en étant de fait une)
