### ISSUE TITLE
Apache configuration (alternc.conf) is not deployed on new installations

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#281]
The symbolic link from /etc/apache2/conf-available/alternc.conf to /etc/alternc/apache2.conf is not created in new installations of AlternC 3.5.0~rc1. The admin panel is available only in https as a result.

**Comment by kienanstewart** [comment]
I think it got accidentally removed in commit 1bc8b59da919daaba63f9870e42a3aa8e28dbeec

**Comment by camlafit** [comment]
was merged
