### ISSUE TITLE
Roundcube webmail access doesn't work in 3.5.0~rc1

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#285]
When accessing roundcube an error message is produced: unable to load config.inc.php

A hook called during alternc.install chowns some the config to be owned by alternc-roundcube, but the roundcube vhosts use www-data:www-data.

There are also old apache 2.2 permissions in the roundcube vhost template

**Comment by quenenni** [comment]
I just installed the same build on a debian stretch.

alternc-install return this error about roundcube:
```
chown: impossible d'accéder à '/etc/roundcube/main.inc.php': Aucun fichier ou dossier de ce type
```
I didn't yet test it because I have other problems to fix first, but maybe it's linked to your problem..

**Comment by camlafit** [comment]
PR has been merge , we can close
Please to open a new issue if required , thanks
