### ISSUE TITLE
DNS regeneration behaviour in PHP does not match the bash version

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#287]
In 3.5.0~rc1 the zones are regenerated twice in some cases (eg. when rebuild_all_webconf.sh) is called. However, the behaviour between the generation is in update_domains.sh and generate_bind_conf.php is slightly different.

In update_domains.sh (or more precisely, in functions_dns.sh) /usr/lib/alternc/reload.d is called with dns_reload_zone *before* bind9 is reloaded; but in class_system_bind.php::regenerate_conf reload.d is invoked after bind is reloaded. It is useful to invoke reload.d before hand since there is no otherway to modify zone files before a reload currently.

Furthermore, the invocation of scripts by directory is not working in m_hooks.php due to a small bug where the directory name is not prepended to file the names when scanning the directory for executable scripts.

**Comment by kienanstewart** [comment]
PR #288

**Comment by camlafit** [comment]
No more related with differents core change
cf #288 for more information
