### ISSUE TITLE
alternc-roundcube -- manque "roundcube-plugins-extra"

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#29]
Il manque la dépendance du paquet `alternc-roundcube` vers le package `roundcube-plugins-extra` qui permet entre autre la gestion des filtres sieves.

**Comment by vincib** [comment]
nope, roundcube-plugins contient déjà "managesieve" qui ajoute "Filter" aux préférences, en mode graphique. un autre plugin similiaire, "sieverules" est dans roundcube-plugins-extra, mais pas requis ni configuré par AlternC.
