### ISSUE TITLE
Bad information on delete account

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#298]
![alterncdeleteaccount](https://user-images.githubusercontent.com/209915/45448092-d1423f80-b6d1-11e8-8083-7956dff509fd.png)
As you can see account deleted is "batisseur", and we can see a confirmation about adm.

Looks as an error on the information

**Comment by albancrommer** [comment]
Hi. This is a bit complicated : 
  * The "2004_myadm" user is the phpmyadmin SSO's user attached to the user
  * It gets deleted as well, by design
  * The message is unclear for the end user, but the system works as expected.

Not sure what I should do about that. Filter the message ? Do nothing ?

**Comment by camlafit** [comment]
Maybe said : 
 mysql user(s) has/have been deleted
 ftp user(s) ...
