### ISSUE TITLE
Config file format changed in the upgrade to 3.2.10 => 3.3.11

### ISSUE THREAD

**Issue by GuillaumeFromage** [AlternC/AlternC#310]
In the upgrade to 3.3.11 I had to manually specify MYSQL_USER and MYSQL_PASS in local.sh, for some reason it needed that to connect to mysql.

**Comment by camlafit** [comment]
Hello

Indeed some variables are only set in debconf and not saved in local.hs
In my mind problem is not specific to this use cas but local.sh vs debconf.

I propose to open a specific issue about this and close this current as sub issue
