### ISSUE TITLE
Feature request : ajouter un "one time link" au lieu du mot de passe à la création d'un compte alternc 

### ISSUE THREAD

**Issue by sebas891** [AlternC/AlternC#319]
Comme administrateur Alternc, on doit communiquer le mot de passe du compte Alternc au responsable du compte.  On demande d'aller changer le mot de passe, mais on n'a pas de mécanisme pour forcer le changement seulement la bonne volonté du responsable.

Il serait beaucoup plus sécuritaire de communiquer un lien que le responsable pour ouvrir seulement une fois pour aller configurer le mot de passe.  Ça éviterait d'envoyer des mots passe...

Non, j'ai pas de PR de cuisiné malheureusement...

J'imagine que ça implique minimalement, un changement dans le formulaire de création du compte pour donner l'option.

**Comment by lelutin** [comment]
Salut! je crois que cette feature serait en fait remplie par #307 si après la création d'un compte, on demande à la nouvelle personne d'initier un "password reset". La pull request implémente les liens à usage unique via le reset de mot de passe.

**Comment by kienanstewart** [comment]
@sebas891 serais-tu à l'aise que je ferme cette demande comme doublon de #307? Ou, y-a-t-il une fonctionalité ici que l'autre ne pourrait pas remplir?

**Comment by sebas891** [comment]
@kienanstewart  oui merci pour le suivi. Je ferme si je peux la demande.
