### ISSUE TITLE
Minor detail in the form "Add an IP or a networks"

### ISSUE THREAD

**Issue by santiagomr** [AlternC/AlternC#326]
Hi. I report a minor detail in the form `Add an IP or a networks`, in which the titles of the fields are inverted. [This](https://github.com/AlternC/AlternC/blob/7a6d800e21b9d3fc1b2ad26fef5159e95fd84954/bureau/admin/ip_main.php#L210) is the line of code in question.

This form can be found at: `https://my-alternc-instance.net/ip_main.php`

**Comment by camlafit** [comment]
Hello

Thanks a lot for you report. Could be possible to provide an PR ?

Thanks a lot
