### ISSUE TITLE
entrées bind dupliquées

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#328]
La mise à jour vers la version 3.5.0~rc1+0~20190329152 m'a dupliqué en boucle les entrées de toutes mes zones bind (@ IN A  dupliqué 143 fois, @ IN MX 5  69 fois ...)

**Comment by lelutin** [comment]
allô! pour tenter de reproduire ce problème, ça nous prendrait un peu plus d'information:

la mise à jour était faite à partir de quelle version?

la version 3.5.0 vers laquelle tu a upgradé, c'était un package .deb, il venait du repos http://debian.alternc.org/ ? ou bien de celui de Koumbit, http://debian.koumbit.net/debian/ ?

**Comment by ddeenniiss** [comment]
Le paquet du dépôt Koumbit. Et à priori, je venais de la dernière version du dépôt http://stable-3-5.nightly.alternc.org soit 3.3.11~zznightly201806220201

**Comment by ddeenniiss** [comment]
Et pour info j'ai aussi fait juste avant une mise à jour de alternc-certificate-provider-letsencrypt

0.0.15-190115175730 vers 0.0.15-190325175634 depuis le dépôt https://dl.bintray.com/alternc/

**Comment by kienanstewart** [comment]
J'ai vue la même chose cette semaine avec le build le plus récent.

**Comment by kienanstewart** [comment]
PR #331

**Comment by ddeenniiss** [comment]
Juste pour pas oublier: https://github.com/Koumbit/AlternC/commit/9c94ac78d34842b5ccb0dbe6d6e10da3d8dceb0a
