### ISSUE TITLE
[dovecot] fichier 96_ssl.conf

### ISSUE THREAD

**Issue by nahuelange** [AlternC/AlternC#33]
Suite à la mise à jour, le fichier 96_ssl.conf dans lequel j'avais des conf perso a disparu, il est revenu dans la forme d'origine proposée par alternc, alors qu'il n'y a pas de template dans /etc/alternc/templates.

**Comment by vincib** [comment]
alternc.install contains the following code: 
                                                                                                         
	( echo "ssl_cert = </etc/alternc/apache.pem" ; echo "ssl_key = </etc/alternc/apache.pem" ) >/etc/dovecot/conf.d/96_ssl.conf

I added a comment to it ;) you can overwrite ssl settings in a 99_ssl.conf file (or anything above 96)
