### ISSUE TITLE
Patch pour faire fonctionner la désactivation d'un sous-domaine dans la version 3.5.0

### ISSUE THREAD

**Issue by hb9tuh** [AlternC/AlternC#330]
Un petit patch sur le fichier panel/class/m_dom.php que j'ai créer afin que la désactivation d'un sous-domaine fonctionne chez-moi. Il semble que le passage de l’état DISABLED à DISABLE n'était pas  gérer correctement par le script cron /usr/lib/alternc/update_domains.php.
Voici le patch:
[m_dom.php.patch.txt](https://github.com/AlternC/AlternC/files/3052276/m_dom.php.patch.txt)

**Comment by camlafit** [comment]
Bonjour

Vu que #350 semble tres proche je note ce ticket en duplicate et invite à continuer la discussion sur #350 

Merci
