### ISSUE TITLE
phpmyadmin 

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#335]
Dans administration, Phpmyadmin, le lien ne fonctionne pas et donne une erreur "La page n’est pas redirigée correctement"

Dans les logs:

```
phpmyadmin: Failed to load /var/lib/phpmyadmin/blowfish_secret.inc.php Check group www-data has read access and open_basedir restrictions., referer: https://xxx/adm_panel.php

phpmyadmin: Failed to load /var/lib/phpmyadmin/config.inc.php Check group www-data has read access and open_basedir restrictions., referer: https://xxx/adm_panel.php
```
version 3.5.0~rc1+0~20190412204409.39~1 depuis le dépôt koumbit

**Comment by quenenni** [comment]
On a finalement pu régler ces différents problèmes.

1.
> Dans administration, Phpmyadmin, le lien ne fonctionne pas et donne une erreur "La page n’est pas redirigée correctement"

A l'installation d'AlternC, il configure phpmyadmin pour utiliser les Cookies et s'y connecter auto.
Cela fonctionne quand on se connecte à un compte normal d'AlternC et qu'on clique sur le lien PhPMyAdmin (qui appelle https://xxxxx.net/sql_pma_sso.php).

Par contre, si on est connecté au compte admin d'AlternC, cliquer sur le lien PhPMyAdmin de la section Administration (qui appelle https://xxxxxxxx.net/alternc-sql/) renvoie l'erreur donnée ci-dessus.

Cela car si la connexion via cookies ne fonctionne pas, AlternC lui dit d'aller à la page "/alternc-sql/index.php?server=2';", mais y a pas de config pour $cfg['server'][2].

Pour résoudre ça, j'ai ajouté dans le fichier /etc/alternc/phpmyadmin.inc.php :
```
// Server #1 in db_servers
$i++;
$cfg['Servers'][$i]['connect_type']  = 'socket';    // How to connect to MySQL server ('tcp' or 'socket')
$cfg['Servers'][$i]['auth_type']     = 'cookie';    // Authentication method (config, http or cookie based)?
$cfg['Servers'][$i]['hide_db']       = 'information_schema';
$cfg['Servers'][$i]['verbose']       = 'Default'; // human name
```
Maintenant AlternC va rediriger vers la page de login de PhpMyAdmin s'il ne peut pas se connecter via Cookies.

2.
> phpmyadmin: Failed to load /var/lib/phpmyadmin/blowfish_secret.inc.php Check group www-data has read access and open_basedir restrictions., referer: https://xxx/adm_panel.php
>
> phpmyadmin: Failed to load /var/lib/phpmyadmin/config.inc.php Check group www-data has read access and open_basedir restrictions., referer: https://xxx/adm_panel.php

Ce sont des erreurs dans les logs qui n'ont pas de conséquence à part remplir les logs.

On peut résoudre ce problème, mais de toute façon, la config blowfish_secret est définie dans /etc/alternc/phpmyadmin.inc.php et non dans /var/lib/phpmyadmin/.

Pour ne plus avoir ces erreurs:
* changer les droits sur ces 2 fichiers (mettre en 0644). Mais cela rend ces 2 fichiers en lecture pour tout le monde. Ceci dit, ces 2 fichiers n'ont pas d'infos dangereuses à montrer (l'un est vide et l'autre à une config qui n'est pas celle utilisée.

* ajouter l'utilisateur altercpanel au groupe www-data.
Mais est-e que ce n'est pas dangereux de faire ça. Y a peut-être ( sans doute ) des conséquences cachées.

Pas trop sûr de savoir laquelle appliquer. 

3.
Une fois réglé ces problèmes, PhpMyAdmin fonctionne bien.
Juste une erreur qui s'affiche: "La phrase secrète de la configuration (blowfish_secret) est trop courte."

Et en effet, le $cfg['blowfish_secret'] dans le fichier /etc/alternc/phpmyadmin.inc.php ne contient que 24 cars.
Une fois passé à 32 cars, phpMyAdmin n'a plus d'erreur.

**Comment by kienanstewart** [comment]
Salut,

dans ce que j'ai vu à date le cas 1) soulèvé par @quenenni survient lors d'une nouvelle installation. Si je roule alternc.install une deuxième fois, le fichier a bien la 2ème entrée.

Pour ce qui est le 2ème point, je propose appliquer un acl sur ces deux fichiers lorsque alternc.install est roulé: eg. `setfacl -m g:alterncpanel:rx /var/lib/phpmyadmin/*.php`. L'application a déjà un pre-depends sur acl donc on peut présumé que c'est présent et fonctionnel?

Je propose également de changer le lien "alternc-sql" dans le menu admin pour the sql_pma_sso.php. Le script sql_pma_sso.php créera le cookie au besoin, donc devrait marcher plus systématiquement que `/alternc-sql`. `/alternc-sql` fonctionnera seulement une fois que le cookie est créer une première fois.

Je pense en plus, ça serait nice que sql_pma_sso.php ne fait pas de redirection et laisse une message à l'utilisateur/trice si jamais il n'y pas de bases de données créés dans le compte. Dans ce cas là, la connection avec PHPMyAdmin ne fonctionnera pas de tout de ce que je vois.

**Comment by kienanstewart** [comment]
Ou, autre qu'un ACL, je vois que alternc.install utilise déjà dpkg-statoverride sur `/var/lib/phpmyadmin/tmp` et `/etc/phpmyadmin/config-db.php` donc on pourrait suivre cette ligne existante pour appliquer les changements de owner/group

**Comment by quenenni** [comment]
Je n'ai pas d'avis sur la résolution du point 2 (par manque de connaissance à ce sujet).

Je suis pour que cliquer sur le lien renvoie un msg à l'utilisateur s'il n'a pas de Db dans son compte.

**Comment by kienanstewart** [comment]
J'ai proposé un PR qui est encore en "WIP", #347. Il reste à trouver une solution pour les cas où l'entrée auto-generated n'est pas ajouté au fichier phpmyadmin.inc.php.

**Comment by kienanstewart** [comment]
J'ai trouvé l'enjeu avec les nouvelles installations: dans alternc.install, lorsqu'une nouvelle installation est detecté (c'est à dire - le compte admin n'existe pas encore), le script newone.php est executé. C'est dans ce script que le serveur de base de données par défaut est défini. Mais là, ça arrive après que tout les fichiers de config sont déjà templaté, donc il n'a pas d'entrées dans db_servers pour phpmyadmin.inc.php.

Je pense que la solution à celà est de passer ce script plus tôt avant que le templating soit fait.

**Comment by kienanstewart** [comment]
le PR est prêt d'être tester / valider
