### ISSUE TITLE
non-suppression d'un domaine

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#336]
A la suppression d'un domaine, celui-ci reste bloquer dans l'interface "Vous avez demandé la suppression du domaine"

Dans la table domaines:

5 | 2001 | toto.be | 1 | 1 | 0 | DELETE |   | 3600

Install sur stretch, avec la version 3.5.0~rc1+0~20190412204409.39~1 de koumbit

**Comment by quenenni** [comment]
* fichier class/m_dom.php (ligne 1931):
```
$db->query("DELETE FROM domaines WHERE domaine=?;",array($onedom["domaine"]));
```
J'ai ajouté le ["domaine"] à l'array $onedom sans quoi la requête n'est pas bonne.

**Comment by kienanstewart** [comment]
Merci du rapport @ddeenniiss  et @quenenni de pointer le fix. J'ai ouvert un PR #343 pour le regler.
