### ISSUE TITLE
suppression d'un domaine, entrée + clef dkim pas supprimé

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#338]
la supression d'un domaine ne supprime pas les entrée dans la table sub_domaines, il reste l'entrée alternc._domainkey

C'est bloquant si on supprime un domaine pour le réinstaller, alternc dit qu'il existe déjà.

Ps: Les fichiers opendkim ne sont pas supprimés

**Comment by kienanstewart** [comment]
Merci du rapport @ddeenniiss , j'ai fait un PR #344 qui devrait addresser ces deux bogues.

**Comment by ddeenniiss** [comment]
Effet de bord, un domaine supprimé ne peut plus être réinstallé tant que cette entrée dkim n'est pas supprimée

**Comment by camlafit** [comment]
looks solve with #345
reopen if required 

thanks
