### ISSUE TITLE
Correction bugs v3.5  dans le fichier m_bind.php function conf_from_db

### ISSUE THREAD

**Issue by hb9tuh** [AlternC/AlternC#339]
J'ai détecté un petit bug  dans la v3.5-rc1, la requête utilisée pour générer les ligne dns pour bind dans la fonction conf_from_db ne sélectionne  pas le domaine. Cela fonctionne bien avec un seul domaine mais c'est out si il y en plusieurs.
Il faut juste rajouter la ligne "AND sd.domaine='$domain'" après la clause WHERE comme ci-dessous:

        SELECT 
          REPLACE(REPLACE(dt.entry,'%TARGET%',sd.valeur), '%SUB%', if(length(sd.sub)>0,sd.sub,'@')) AS ENTRY 
        FROM 
          sub_domaines sd,
          domaines_type dt 
        WHERE 
          sd.type=dt.name
          AND sd.enable IN ('ENABLE', 'ENABLED') 
          AND sd.domaine='$domain'
        ORDER BY ENTRY ;");

 
Il y a également une faute de frappe dans la fonction domains_type_update du fichier m_dom.php à la ligne 563. Il y a la lettre e à la place d'un ?. Ceci interdisait de modifier le champ  only_dns et avait quelques effets pervers.

**Comment by kienanstewart** [comment]
Salut @hb9tuh , merci d'avoir rapporté ces problèmes en détail. J'ai ouvert un PR #342 avec les changements
