### ISSUE TITLE
Undefined offset sur update_domains sur un domaine fraichement importé

### ISSUE THREAD

**Issue by dauge** [AlternC/AlternC#341]
Sur une installation jessie fraiche, sur le premier domaine dont j'importe la définition DNS, j'obtiens le mail suivant à la regénération DNS

> dns_regenerate : domain=/domain.net/
> PHP Notice:  Undefined offset: 2 in /usr/share/alternc/panel/class/m_err.php on line 152
> zone reload up-to-date
>

**Comment by kienanstewart** [comment]
Salut dauge, est-ce la version 3.5 ou la version 3.3?

**Comment by dauge** [comment]
C'est la version 3.3

**Comment by camlafit** [comment]
closed by  43d97f1 took from 2a07927acc67508073ff76470fd69442a42e36ed
