### ISSUE TITLE
Panel bug logout

### ISSUE THREAD

**Issue by petit42** [AlternC/AlternC#37]
Panel logout if switch ipv4 to ipv6 (same ipv6 to ipv4)

**Comment by innoticFR** [comment]
Sessions are restricted to IP.

There was a checkbox to force or unforce this restriction before on the login page, which is now an hidden field.  This was done in 9517d27d78e38ee0af8824f688f8180599466da1 but the choice to remove this checkbox was not explained.

**Comment by vincib** [comment]
I propose that we remove this feature altogether : it's bugguy and we can't handle ipv4/ipv6 switch properly.

**Comment by lelutin** [comment]
I second the removal. other means could be used, like auth cookies, instead of limiting to IP.

**Comment by innoticFR** [comment]
I set the default value to 0 in admin/index.php, leaving the chance to go back one day, or to customize it if needed.
