### ISSUE TITLE
doublons dans default_subdomains

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#38]
Domi a créé un ticket concernant un probleme de doublons dans
default_subdomains : http://alternc.org/ticket/1662

et commis 2 patchs qui le corrigent dans la branche stable-3.1 :
(en 2 fois, comme ça l'un peut etre défait si besoin sans impacter
l'autre)

http://git.alternc.org/projects/alternc.git/commits/7c0e7c9
http://git.alternc.org/projects/alternc.git/commits/b379d2c

Le premier, ca ajoute juste le UNIQUE KEY manquant quand on fait une
install fraiche

Pour le deuxieme, par contre, je sais pas exactement dans quels cas cela
se produit vraiment.
A priori, alternc.install ne devrait jouer que les scripts nécessaires,
mais dans ce cas je n'aurai jamais du rencontrer de doublon.
Or, j'ai au moins 2 installations où ça s'est produit...

**Comment by vincib** [comment]
Patches from domi 7c0e7c953cc13d20a2a8edf3ecd27cfc347c8520 b379d2cb34adaebc067a0cd2a7da679f6ccd203b
