### ISSUE TITLE
alternc.install etckeeper integration

### ISSUE THREAD

**Issue by GuillaumeFromage** [AlternC/AlternC#389]
Hi,

Often we don't really know what alternc.install does. It would be nice to just have a "alternc.install.pre hook", or to just to git commit /etc/ with a nice commit message if package etckeeper is installed. This way, all the changes made by the script are neatly consigned in a place for future reference.

G

**Comment by camlafit** [comment]
Hello

I'm not sure could be a correct solution. In my mind will not fix. 
We have two options 
* in your local context create a personal wrapper to this specific use case
* generalize hook on all alternc object (but this case should be describe in other issue)

Then I tag as wontfix but maintained it opened to continue discussion

**Comment by GuillaumeFromage** [comment]
Sweet thanks.
