### ISSUE TITLE
avelsieve pas dans les dépôts

### ISSUE THREAD

**Issue by nahuelange** [AlternC/AlternC#39]
Lors de l'installation d'alternc-squirrelmail : 
```
alternc-squirrelmail : Dépend: avelsieve mais il n'est pas installable
```
parce qu'il n'est plus présent dans les dépôts de wheezy

**Comment by skhaen** [comment]
alternc-squirrelmail n'est plus utilisé en debian wheezy il me semble, il est remplacé par alternc-roundcube.

**Comment by nahuelange** [comment]
Mais le paquet continue d'exister, soit faut trasher le paquet, soit le réparer. Ce qui est d'autant plus "bizarre" c'est que le paquet pour squeeze s'installe sans problème en wheezy. Il y a peut-être le mainteneur qui ne répond plus présent.

**Comment by vincib** [comment]
Je propose que nous packageions avelsieve dans le dépot WHEEZY d'AlternC, en backportant celui de jessie. passe nickel pour moi.

publié à l'instant :) 

http://debian.alternc.org/dists/wheezy/main/binary-all/web/
```
Format: 1.8
Date: Sat, 27 Aug 2016 11:50:00 +0200
Source: avelsieve
Binary: avelsieve
Architecture: source all
Version: 1.9.9-2.4~alternc.1
Distribution: unstable
Urgency: low
Maintainer: Jan Hauke Rahm <jhr@debian.org>
Changed-By: Benjamin Sonntag <benjamin@octopuce.fr>
Description: 
 avelsieve  - Sieve mail filters plugin for SquirrelMail
Changes: 
 avelsieve (1.9.9-2.4~alternc.1) unstable; urgency=low
 .
   * Backport for Wheezy


```

**Comment by vincib** [comment]
republished, reclosed
