### ISSUE TITLE
forcer le ssl pour l'accès à l'admin

### ISSUE THREAD

**Issue by nahuelange** [AlternC/AlternC#40]
Je crois que c'était le cas avant, mais aujourd'hui je trouve pas,
il y avait une option de conf pour forcer le ssl sur le panel alternc, ce serait bien de la remettre et/ou la documenter.

**Comment by innoticFR** [comment]
This was removed by commit bbd913e6e6c3e46edd41af511192c9096e45fd97
"completely revert [1025] since we rely on apache config to enable/disable ssl/non-ssl now"

But this is was big regression.
