### ISSUE TITLE
Debian buster: bug in file manager

### ISSUE THREAD

**Issue by ulvida** [AlternC/AlternC#405]
On a fresh alternc, installed in a fresh buster, when I visit the File Manager of the panel menu I have a broken page: 
![imagen](https://user-images.githubusercontent.com/24596190/73268753-4d9bcc80-41ba-11ea-84be-359727a71015.png)
The page appears for a fraction of second when reloading the page and goes to the broken page.

**Comment by ulvida** [comment]
In the logs, ther is a php notice: 
```
[Tue Jan 28 12:27:21.420142 2020] [php7:notice] [pid 4600] [client <my_IP>:34174] PHP Notice:  A non well formed numeric value encountered in /usr/share/alternc/panel/admin/bro_main.php on line 57, referer: https://anacahuita.interior.edu.uy/main.php
```

**Comment by kienanstewart** [comment]
Duplicates #402

**Comment by ulvida** [comment]
The previous PHP warning has nothing to do with the frontend error. 

In fact, it seems to be a problem with the new version of the library `jquery.tablesorter.min.js`provided by debian package  `libjs-jquery-tablesorter`, version `1:2.31.1+dfsg1-1`.

**Comment by camlafit** [comment]
Hello

As duplicate continue on #402 
thanks :)
