### ISSUE TITLE
Add debian changelog notice to 3.5rc2 and try to limit upgrades to happening only from 3.x.12

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#415]
From meeting 2020-06-05

**Comment by kienanstewart** [comment]
Related #397  ; #374

**Comment by kienanstewart** [comment]
Debian policy on news and changelogs in packages : https://www.debian.org/doc/debian-policy/ch-docs.html#changelog-files-and-release-notes
Debian policy on maintainer scripts: https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#summary-of-ways-maintainer-scripts-are-called

An alternc.preinst script could be added to prompt the user to accept continuing if the version is < 3.3.12.

**Comment by kienanstewart** [comment]
https://www.debian.org/doc/debian-policy/ch-binary.html#s-maintscriptprompt suggests that the prompt should actually be in config instead of preisnt. The other suggested placement, postinst, is too late for our desired outcome.

```
If a package has a vitally important piece of information to pass to the user (such as “don’t run me as I am, you must edit the following configuration files first or you risk your system emitting badly-formatted messages”), it should display this in the config or postinst script and prompt the user to hit return to acknowledge the message. Copyright messages do not count as vitally important (they belong in /usr/share/doc/package/copyright); neither do instructions on how to use a program (these should be in on-line documentation, where all the users can see them).
```

**Comment by kienanstewart** [comment]
From the man page for dpkg though, the actual installation process is:

 * extra control files of new package
 * run "prerm" of old package, if another version was installed
 * run preinst script
 * unpack new files
 * run "postrm" of old package
 * package configuration

So preinst, depiste the policy suggestions, seems to be the appropriate place

**Comment by kienanstewart** [comment]
PR #437

**Comment by camlafit** [comment]
add a notice  about dmarc #441
