### ISSUE TITLE
Messages class not loaded for connections to the API endpoint

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#419]
The API is bootstrapped in admin/api/bootstrap.php, which does load the class m_messages into the global variable $msg. As a result many API calls will fail as function expect this variable to be set.

**Comment by kienanstewart** [comment]
An aside: is there a particular reason the API bootstrap code is different than the regular bootstrap process?

**Comment by lelutin** [comment]
I'll add a clarification to this: this effectively means that authentication with the API is impossible in the current state of the code.
