### ISSUE TITLE
sur Buster Incrond accumule plusieurs processus 

### ISSUE THREAD

**Issue by sebas891** [AlternC/AlternC#424]
On constate que la load augmente sur un serveur, il y a 4900 processus incrond. 
La version du alternc est 3.5.0~rc1+0~20191218224408.56~1.gbpc68e97 (version Koumbit)

```
cat /etc/incron.d/alternc_do_action
/run/alternc/ IN_CREATE,IN_ATTRIB,IN_NO_LOOP /usr/lib/alternc/inotify_do_actions.sh
cat /etc/incron.d/alternc_update_domains 
/run/alternc/ IN_CREATE,IN_ATTRIB,IN_NO_LOOP /usr/lib/alternc/inotify_update_domains.sh
```
Si vous avez des pistes sur comment débugger ça.

**Comment by sebas891** [comment]
Sur irc!

```
11:54 <@viashimo> 08:43 < emile_> mais depuis que j'ai déplacé le 
                  dossier à surveiller dans /run/alternc/incron plus 
                  de pb

```

**Comment by sebas891** [comment]
On peut faire "incrond -k" pour tout tuer les processus.

**Comment by kienanstewart** [comment]
I tried changing the directory, and it's a partial improvement: incrond no longer starts processes when the various job lock files are created and destroy; however, actual incrond trigger files are created processes tend to still pile up without quitting.

Eg. ```
incrond -k
incrond -n # start in foreground for debugging
root@debian-10-amd64:/home/vagrant# ps faux | grep incron  
root     29007  0.0  0.1   9576   824 pts/1    S+   18:13   0:00  |   \_ grep incron   
root     28992  0.0  0.6   5760  3376 pts/2    S+   18:13   0:00      \_ incrond -n    
root@debian-10-amd64:/home/vagrant# touch /run/alternc/incron/inotify_update_domain.lock
root@debian-10-amd64:/home/vagrant# ps faux | grep incron                           
root     29024  0.0  0.1   9576   888 pts/1    S+   18:13   0:00  |   \_ grep incron
root     28992  0.0  0.6   5760  3408 pts/2    S+   18:13   0:00      \_ incrond -n    
root     29009  0.0  0.0   5760   252 pts/2    S+   18:13   0:00          \_ incrond -n
root     29010  0.0  0.0   5760   256 pts/2    S+   18:13   0:00          \_ incrond -n
root     29011  0.0  0.0   5760   256 pts/2    S+   18:13   0:00          \_ incrond -n
```

And these sub processes don't go away. Each time the file is touched, for example, children continue to pile up.

**Comment by kienanstewart** [comment]
I changing the directory is worthwhile, just ot avoid the process spam by default. I'm not really sure that the incron.d checks are doing anything very useful right now:

 * the INOTIFY_UPDATE_DOMAIN is not written to in the core codebase (although, maybe there are plugins somewhere that depend on the functionality?)
 * actions and update_domains are still run via cron job by default

In testing, the actions I seem to have uncovered another bug where there are errors with the actions saving their success (or failure) state into the database. When ran with debug set to '1' in the script: Eg.

```
# /usr/lib/alternc/do_actions.php 
-----------
Beginning action n°2
Executing action 'FIX_USER' with user 'root'
Finishing... return value is : OK

errors were metarray(1) {
  [0]=>
  string(127) "Cannot finish the action! Error while inserting the error value in the DB for action n°2 : action 'FIX_USER'
Return value: OK
"
}
root@debian-10-amd64:/etc/incron.d# mysql alternc -e "select * from actions;"
+----+----------+------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+------+--------+
| id | type     | parameters                                                                                     | creation            | begin               | end                 | user | status |
+----+----------+------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+------+--------+
|  2 | FIX_USER | a:1:{s:3:"uid";i:2000;}                                                                        | 2020-10-13 17:46:25 | 2020-10-13 18:44:33 | 0000-00-00 00:00:00 | root |   NULL |
|  3 | CHMOD    | a:2:{s:8:"filename";s:45:"/var/www/alternc/a/admin/www/example.com/asdf";s:5:"perms";i:33204;} | 2020-10-13 18:32:45 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | root |   NULL |
|  4 | CHMOD    | a:2:{s:8:"filename";s:41:"/var/www/alternc/a/admin/www/example3.com";s:5:"perms";i:16744;}     | 2020-10-13 18:41:29 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | root |   NULL |
|  5 | CHMOD    | a:2:{s:8:"filename";s:41:"/var/www/alternc/a/admin/www/example2.com";s:5:"perms";i:16744;}     | 2020-10-13 18:42:25 | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 | root |   NULL |
+----+----------+------------------------------------------------------------------------------------------------+---------------------+---------------------+---------------------+------+--------+

```

**Comment by kienanstewart** [comment]
Once I fixed the problems in do_actions.php, the incrond spam stopped. Maybe incrond was having a hard time with the scripts having errors of some sort? I don't really know enough to answer that question right now. I will propose both the fix for do_actions and the relocation of the incron watched directory as PRs

**Comment by vincib** [comment]
also, for your information 
https://github.com/AlternC/AlternC/pull/430#issuecomment-758082893
