### ISSUE TITLE
Buster: UPDATE répétitif de domaines

### ISSUE THREAD

**Issue by WhilelM** [AlternC/AlternC#425]
Sur une installation buster Alternc 3.5.0~rc1+0~20191218224408.56~1.gbpc68e97 (Koumbit), des mises à jour sont effectuées toutes les minutes
Jul 15 06:01:01 panel1 named[564]: sizing zone task pool based on 8 zones
Jul 15 06:01:01 panel1 named[564]: zone zone1.eu/IN: loaded serial 2020085567
Jul 15 06:01:01 panel1 named[564]: zone zone2.fr/IN: loaded serial 2020085570
Jul 15 06:01:01 panel1 named[564]: zone zone3.net/IN: loaded serial 2020118562
Jul 15 06:02:01 panel1 named[564]: sizing zone task pool based on 8 zones
Jul 15 06:02:01 panel1 named[564]: zone zone1.eu/IN: loaded serial 2020085568
Jul 15 06:02:01 panel1 named[564]: zone zone2.fr/IN: loaded serial 2020085571
Jul 15 06:02:01 panel1 named[564]: zone zone3.net/IN: loaded serial 2020118563

**Comment by WhilelM** [comment]
https://github.com/AlternC/AlternC/issues/413

**Comment by camlafit** [comment]
close as duplicate #413
