### ISSUE TITLE
phpmyadmin showing blank page on ubuntu 20.04

### ISSUE THREAD

**Issue by WybeTuring** [AlternC/AlternC#429]
Just set up phpmyadmin on ubuntu 20.04, but localhost/phpmyadmin shows me only a blank page. I went into my phpmyadmnin folder and tried to run php index.php. The errors were as follows; 

phpmyadmin: Failed to load /var/lib/phpmyadmin/blowfish_secret.inc.php Check group www-data has read access and open_basedir restrictions.
phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php Check group www-data has read access and open_basedir restrictions.

I have been unable to fix this ever since. Some help will be very much appreciated.

**Comment by camlafit** [comment]
Hello

Sorry I'll close this issue. Actually we don't have any plan to support ubuntu. Although some users are succeed installation with this distribution.
