### ISSUE TITLE
Utilisateur ou mot de passe incorrect suite à nouvelle installation

### ISSUE THREAD

**Issue by infoca** [AlternC/AlternC#44]
Bonjour, j'ai suivi le lien de la documentation du site Alternc avec les consignes suivantes à suivre pour l'installation : 

    Clone this repository ex:

    git clone https://www.github.com/AlternC/easy-install.git

    cd easy-install

    ./install.sh

    Follow questions and wait for install to occur

    Profit!

Après accès à l'interface nouvellement créée, le test le couple Login/password d'usine (Admin/Admin) et ça me dit "Utilisateur ou mot de passe incorrect "

plusieurs installations sur plusieurs serveurs différents et toujours pareil.

Une solution ?

merci d'avance.

**Comment by albancrommer** [comment]
Bonjour, nous aurions besoin de plus d'informations pour comprendre ce qui se passe. 

1. A la fin de l'installation, est-ce qu'il y a eu des messages d'erreur ? Est-ce que le panel Alternc est accessible ? 

2. Sur quels types de serveurs (LXC ? KVM ? Baremetal ?) etc.

**Comment by infoca** [comment]
Bonjour, pas de message d'erreur à la fin de l'install tout ce passe bien et l'accès au panel est bien accessible en http.

Installé sur un serveur dédié Debian 7

**Comment by albancrommer** [comment]
Dans ce cas il faudrait vérifier 2 choses : 

1. Est-ce que le panel accède bien à mysql ? 

`mysql --defaults-file=/etc/alternc/my.cnf -e "select count(*) from membres"`

2. Est ce que l'utilisateur admin existe ? 
`mysql --defaults-file=/etc/mysql/debian.cnf alternc -e "select * from membres where login='admin'"`

**Comment by infoca** [comment]
c'est exactement ce que j'étais en train de regarder. Le panel accède bien à mysql (1) par contre je vois aucun user dans la table membres et pourtant il n'a rien indiqué comme erreur lors de l’exécution du script d'install ..  :/ je vais créer un user avec les données obligatoires et je te dis si ça fonctionne

**Comment by infoca** [comment]
ça fonctionne !! c'était un prob du fichier de conf du compte admin (newone.php) qui posait problème.

la valeur : "postmaster@".$L_FQDN n'était pas valide pour la création

j'ai posté le ticket un peu vite .. merci de ton aide en tout cas
