### ISSUE TITLE
Default DMARC entries are not syntactically correct

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#441]
In AlternC 3.5.0rc1, the default DMARC entries are set to

    p=none;pct=100;rua=%%ADMINMAIL%%;aspf=r;adkim=r

The rest of the DMARC entry, `v=dmarc1` is added in m_mail::set_dns_dmarc

There are two problems with the created records:

   1. The value of the `v` tag is case senstive and must be `DMARC1` instead of `dmarc1`
   2. The value of `rua` should have `mailto:` before the e-mail address

(https://tools.ietf.org/html/rfc7489

A correct (complete) entry might look like

    v=DMARC1;p=none;pct=100;rua=mailto:%%ADMINMAIL%%;aspf=r;adkim=r

thanks,
Kienan

**Comment by kienanstewart** [comment]
PR #442

**Comment by vincib** [comment]
This bug will need a php script to fix the existing values in alternc upgraded from 3.x or 3.5~rc

I propose the following way to do it : 

- change the global variable value if it's the stock one, don't change it if it has been changed by the admin
- change all sub_domains entries that contains a rua=address by rua=mailto:address,
