### ISSUE TITLE
AlternC package cannot be installed when sudo-ldap is installed

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#443]
The alternc pacakage depends on sudo, and we sudo-ldap is installed (which provides sudo), the package must be replaced with sudo before the installation can happen.

since the two packages provide the same command, it would be nice to be able to have AlternC installable with either one

**Comment by vincib** [comment]
If sudo-ldap "provides sudo", this should already works, right?

If sudo-ldap is not marked as "provides sudo", I'd say that this is a bug on sudo-ldap side...

that said, it's a no cost for us to support both.

**Comment by camlafit** [comment]
Note : https://sources.debian.org/src/sudo/1.9.5p2-3/debian/control/

sudo-ldap provide yet sudo
