### ISSUE TITLE
AlternC-awstat install fail silently

### ISSUE THREAD

**Issue by bleuchtang** [AlternC/AlternC#444]
Debian package just ignore error on mysql table creation: 
https://github.com/AlternC/AlternC/blob/3c83f33935bdaf0f601b5d5ba096936cfcac0597/debian/alternc-awstats.postinst#L26

If we did insertion manualy, we got this error:
  mysql --defaults-file=/etc/alternc/my.cnf < /usr/share/alternc/awstats.sql
  ERROR 1300 (HY000) at line 13: Invalid utf8 character string: 'Comptes pouvant acc'

**Comment by camlafit** [comment]
related to #141
