### ISSUE TITLE
Workaround and hooks to install AlternC on buster

### ISSUE THREAD

**Issue by ulvida** [AlternC/AlternC#457]
We have been working on [AlternC installation Ansible role](https://github.com/UdelaRInterior/ansible-AlternC), and we are happy we could install everything on buster [with the last versions](https://github.com/UdelaRInterior/ansible-AlternC/tree/buster)

However, we ran over several obstacles, that deserve better to be addressed in AlternC code. I'll report them as bugs and group them hereafter as comments to this issue (or link them in some other way, as labels).

**Comment by ulvida** [comment]
I can't put lables, so the first bug: #458

**Comment by ulvida** [comment]
Second: Problem in `alternc.install`: #459

**Comment by ulvida** [comment]
#402, [addressed here by the role](https://github.com/UdelaRInterior/ansible-AlternC/blob/59252598f3c7c27bfc6216a8a6f68a6479a7eddb/tasks/install-alternc.yml#L64), and already reported here, was fixed in latest commits and already integrated in the Kumbit package. great! I drop it in the role!

**Comment by ulvida** [comment]
Parse apparmor configuration during alternc install: #460

**Comment by camlafit** [comment]
Hello

All related issues are closed, then I close this meta issue. 
Please reopen if needed, thanks a lot
