### ISSUE TITLE
Appropriate handle of php files for ver >= 7

### ISSUE THREAD

**Issue by ulvida** [AlternC/AlternC#459]
[alternc.install](https://github.com/AlternC/AlternC/blob/master/install/alternc.install#L341) dosn't handle correctly php version (line 341). As PHP configuration version for 7.3 is: `/etc/php/7.3/` and not /etc/php7.3/`, supposing this is from now the new files structure, line 341 should be:
```
 if ! [[ "$php" < "7" ]]
```
and not: 
```
if [ "$php" = "7.0" ]
```
(The later only solves the problem for debian stretch, not buster)

**Comment by lelutin** [comment]
I've tested this change on both stretch and buster, and then I also forced the php variable to contain "5.6" since I didn't have a jessie system to test it on, and it worked great.

this'll avoid creating `/etc/php5` on systems that don't have php 5.6 installed.

thanks for this patch!

**Comment by ulvida** [comment]
thanks for your quick feedback! (it's good to see that AlternC community is alive)
