### ISSUE TITLE
[install jessie] alternc.install alternc.ini pour php

### ISSUE THREAD

**Issue by asso-infini** [AlternC/AlternC#46]
alternc.install essaye de déposer un lien dans /etc/$php/conf.d/ qui n'existe pas :
ln -fs /etc/alternc/alternc.ini /etc/$php/conf.d/alternc.ini

On pourrait déposer le lien plutôt dans les dossiers suivants :
- /etc/$php/apache2/conf.d
- /etc/$php/cli/conf.d

**Comment by vincib** [comment]
Fixed at 5bae6babfb2534f6c2364287775e7380eafce342
