### ISSUE TITLE
Parse AlternC / bind9 apparmor configuration

### ISSUE THREAD

**Issue by ulvida** [AlternC/AlternC#460]
When installing Apparmor configuration to allow bind9 to access alternc configuration file is set, but it seems it's not parsed in apparmor. 

After installing `/etc/apparmor.d/usr.sbin.named` file, AlternC installation should run:  
```
apparmor_parser -r /etc/apparmor.d/usr.sbin.named
```
To sort out this problem, in [alternc ansible role](https://github.com/UdelaRInterior/ansible-AlternC), we check if bind9 is down and then [run this command](https://github.com/UdelaRInterior/ansible-AlternC/blob/59252598f3c7c27bfc6216a8a6f68a6479a7eddb/tasks/post-install.yml#L102).

**Comment by camlafit** [comment]
Hello

Could be integrated in next package as AppArmor is enabled since buster
https://wiki.debian.org/AppArmor/HowToUse

**Comment by camlafit** [comment]
duplicate #388
