### ISSUE TITLE
Letsencrypt integration

### ISSUE THREAD

**Issue by vincib** [AlternC/AlternC#47]
Letsencrypt allow us to get free and automated SSL certificates. 

We should use letsencrypt https://github.com/octopuce/acmephpc/ to automate this in AlternC, configuring https automatically

**Comment by albancrommer** [comment]
As the development of the acmephpc client reached a new point, development of this feature can start

cf. https://github.com/octopuce/acmephpc/releases/tag/0.1

**Comment by skhaen** [comment]
add to alternc-ssl ?

**Comment by Nodraak** [comment]
What's up here ? Anything new ?

That would be usefull for marsnet.org's webmail http://rc.marsnet.org/ ;)

**Comment by albancrommer** [comment]
Nothing new, yet it would be pretty much straightforward to implement technically by now.

HARD: UI/UX (many options to add to the interface, error handling) 
MEDIUM : CRON with CERT request for every subdomain (using events?)
EASY : renewal, Apache vhosts

**Comment by camlafit** [comment]
Hi

Follow [alternc-certbot](https://github.com/alternc/alternc-certbot)

**Comment by kent1D** [comment]
I don't see how to create a new cert, is it possible. It should replace the creation of auto signed certs, isn't it?

**Comment by camlafit** [comment]
Hi

Actually panel is managed with **alternc.install** script, don't forget to run it after alternc-certbot installation. Panel certificate will be replace by let's encrypt.

About other domain you must run manually : **/usr/lib/alternc/generate_certbot.php** , next version would do it alone :)
Certificat will be add to ssl page on each alternc account, as script can't know if you want use this feature, you must first enable it each domain.
If a certificate is yet enabled to a domain, alternc should took the more interesting (in our case let's encrypt)

**Comment by tuxayo** [comment]
Hi, is there a documentation somewhere about the integration?
Which could help to check whether an existing install has issues or not.

**Comment by camlafit** [comment]
Hello

did you checked  [alternc-certbot](https://github.com/alternc/alternc-certbot) module ?
