### ISSUE TITLE
New matomo user are not added in the piwik_users table

### ISSUE THREAD

**Issue by Mazamazine** [AlternC/AlternC#486]
When adding a new user, the user is correctly created at Matomo's side. It's not added in the alternC database though.
The query in m_piwik.php (l.122) isn't executed and throw an error HY000:
`Field 'email' doesn't have a default value`

Version: 3.3.12+nmu2

We could simply add the email in the query:

`$ret_value = $db->query("INSERT INTO piwik_users (uid, passwd, login, created_date, email) VALUES ( ?, ?, ?, ?, ?);", array($cuid, md5($user_pass), $user_login, $user_creation_date, $user_mail));`

**Comment by kienanstewart** [comment]
In 3.3.12+nmu2, when installed fresh, the piwik_users table does not have the email column.

From `install/mysql.sql`: ```
CREATE TABLE IF NOT EXISTS `piwik_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL,
  `passwd` varchar(255) NOT NULL,
  `login` varchar(255) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user` (`login`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=18 
```

I don't know how/why the email column exists in the version you tested against. Do you know what use the email column has?

**Comment by kienanstewart** [comment]
To be clear, neither upstream AlternC/AlternC/master nor Koumbit/AlternC/pu have the email column in the piwik_users table either.

**Comment by Mazamazine** [comment]
This issue is indeed in the wrong project. Closing.
