### ISSUE TITLE
Update bind template and set SOA to ns1

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#506]
Hi

When we use external ns1 we can have some trouble with zoncheck. SOA must be have ns name.
Looks better to provide by default ns1 has SOA value and not fqdn as actually
In default configuration ns1 is alternc itself, shouldn't break anything

https://github.com/AlternC/AlternC/blob/master/etc/alternc/templates/bind/templates/zone.template#L10

**Comment by camlafit** [comment]
An use case : 
* register a domain with .it tld at bookyname
* use external dns service as alternc.net
* ask to bmn to use alternc dns 

bmn use zonecheck and refuse to proceed until SOA value is set to any ns server value

**Comment by vincib** [comment]
ok, in fact the issue is within ns1/2.alternc.net, not the fact that the SOA "primary ns" value is NOT one of the NS records 

I registered octopuce.it and the IT register accepted my DNS for primary/secondary.heberge.info although the SOA says the primary is alice.octopuce.fr

We will need to check alternc.net conformity instead

**Comment by vincib** [comment]
and I confirm that from cloudflare forums:
https://community.cloudflare.com/t/changing-domain-names-dns-bookmyname-com-soa-and-any-request-disagree/44184

**Comment by camlafit** [comment]
Bookmyname has confirmed this trick wit it extension. They have removed as doesn't look no more required now.
But BMN use this behavior and expose a SOA related to their public resolver (and not their master).
I've seen also in octopuce internal documentation this trick.

I think we can do this change as we don't have any regression

**Comment by camlafit** [comment]
Hi

As BMN as solved this issue in their part and we have consensus has before.
It's wontfix issue
