### ISSUE TITLE
incron not supported in debian Bullseye

### ISSUE THREAD

**Issue by Mazamazine** [AlternC/AlternC#509]
incron has no installation candidate in debian bullseye (only available through unstable). It's only in stretch / buster / sid:
https://packages.debian.org/buster/incron

The reason seems to be this bug which hasn't moved in years: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947425
It doesn't seems to be maintained anymore... (last commits 5 years ago!), so chances are it's not going to be in bookworm either.

Removing any dependencies to incron and use cronjobs instead when needed would be advisable.

**Comment by fufroma** [comment]
Nowadays incron is in  bullseye-backports and in bookworm
