### ISSUE TITLE
Help domain aide-alternc.org expired

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#517]
The domain aide-alternc.org is expired, and is used as the destination for the "Online help" button in the AlternC panel interface.

There is also no visible way to configure it, although the variable is set initially in config.php.

**Comment by sachaz** [comment]
/usr/share/alternc/panel/class/config.php $help_baseurl

there is references to the url with hardlinks here:
/usr/share/alternc/panel/admin/adm_slavedns.php
/usr/share/alternc/panel/admin/about.php

**Comment by camlafit** [comment]
New website is https://aide.alternc.org
