### ISSUE TITLE
[bug] compress_logs.sh and delete_logs.sh use the same DAYS variable from local.sh

### ISSUE THREAD

**Issue by fulax** [AlternC/AlternC#519]
As a consequence, if we want to override compress_logs.sh defaults of 2, and delete_logs.sh defaults of 366, setting DAYS=90 in local.sh will disable the log compression, eating our storage space.

I propose to use two different variables in local.sh for those two different purposes.

**Comment by camlafit** [comment]
#536 duplicate

**Comment by camlafit** [comment]
close as duplicate
