### ISSUE TITLE
compress_logs.sh and delete_logs.sh use the same DAYS variable

### ISSUE THREAD

**Issue by fulax** [AlternC/AlternC#536]
This prevent customizing the log retention or compression delay in local.sh.

For instance, if I only want to keep 30 days of logs, I can set DAYS=30 in local.sh, but then as compress_logs also read DAYS from local.sh, it won't compress logs after two days.

My current solution is to rename DAYS to DAYS_COMPRESS in compress_logs.sh, to be able to set each behavior in local.sh

**Comment by camlafit** [comment]
cf #556
