### ISSUE TITLE
[paquetage deb alternc] dependance avec quota et mysql-server

### ISSUE THREAD

**Issue by asso-infini** [AlternC/AlternC#57]
Lorsqu'on lance directement l'installation de alternc sur une debian qui vient juste d'être installée, on peut remarquer quelques messages d'erreur sur l'exécution de quota et phpmyadmin tente de s'installer avant mysql-server.

Serait-il possible de lancer l'installation de mysql-server et quota plus en amont dans l'installation de alternc ?

**Comment by innoticFR** [comment]
Salut,

La procédure d'installation décrit bien la nécessité d'installer mysql-server et quota avant:
http://alternc.com/Install-fr

mysql-server n'est pas installé par défaut puisque on veut laisser la possibilité d'utiliser un serveur distant.

La gestion des quotas est quant à elle facultative.

**Comment by asso-infini** [comment]
les paquets mysql-server et quotas sont sensés être facultatifs, mais quand on lance la commande "apt-get install alternc", celle-ci installe quand même les paquets quotas et mysql-server.

Est-il possible de, soit rendre l'installation totalement facultative, soit améliorer la gestion les dépendances entre mysql-server, quotas et alternc ?

**Comment by asso-infini** [comment]
enfin pour le paquet quota, je ne suis plus sûr, mais il y a en tout cas des messages qui indiquent que quota n'est pas installé, on pourrait croire que ces messages sont des messages d'erreur.
