### ISSUE TITLE
file browser: impossible de télécharger des gros fichiers

### ISSUE THREAD

**Issue by lelutin** [AlternC/AlternC#59]
Salut,

qqun sur notre hébergement tentait de télécharger un log d'owncloud qui était rendu à 300Mb. quand on clique sur "Télécharger" pour le fichier, on a instantannément une erreur comme celle-ci:

~~~
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 313072566 bytes) in /usr/share/alternc/panel/class/m_bro.php on line 808
~~~

On dirait que m_bro.php lis tout le contenu du fichier en mémoire avant de l'envoyer vers l'utilisateur/utilisatrice.

Je n'ai pas encore inspecté le code autour de la ligne mentionnée dans l'erreur, mais ça serait bien de faire en sorte que le file browser ne fasse qu'utiliser un mmap, ou bien utilise des fonctionnalités d'apache pour streamer le fichier direct sans le charger en mémoire.

**Comment by lelutin** [comment]
je vois selon le code que le problème est que le file browser veut afficher le contenu du fichier parce que c'est du texte (ou plutot pas un type spécial connu).

p-e qu'une solution simple serait d'avoir une conditionnelle sur la taille du fichier avant de se rendre à l'affichage du fichier. qqch du genre "si la taille est plus petite que XYZ, afifcher le contenu, sinon envoyer le fichier comme téléchargement"

**Comment by innoticFR** [comment]
Le gestionnaire de fichiers renvoyait vers la page d'édition en mode d'affichage deux ou trois colonnes.

Par ailleurs, effectivement,si le type détecté est du texte il propose d'ouvrir le fichier en mode d'édition.

J'ai modifié le comportement afin qu'il vérifie que la taille soit inférieure à la valeur de memory_limit de PHP (767044fcb57c8c729f43f6ed0ca1f65d10c9d218).

Dans tous les cas, il existe un lien V/Voir à droite du nom du fichier qui permet de télécharger le fichier directement
