### ISSUE TITLE
alternc-sshusers

### ISSUE THREAD

**Issue by vincib** [AlternC/AlternC#62]
We want to developp a plugin for AlternC, that would synchronize the /etc/passwd /etc/group and /etc/shadow of the system using the same UID/GID (2000+)

(Octopuce started this one, a few bugfixes should be done)

**Comment by innoticFR** [comment]
I thought it would be easy with libnss-mysql-ng and pam-mysql, but libnss-mysql-ng is no longer available as the debian package has been orphaned.

I think the best solution would be to use libnss-extrausers in order not to overwrite system files. pam-mysql might still be useful for the auth part as it would permit to limit file generation to new account creation (only for NSS needs).

**Comment by camlafit** [comment]
looks closed by https://github.com/AlternC/alternc-nss/
