### ISSUE TITLE
Noms de domaines vus comme des regexp

### ISSUE THREAD

**Issue by denis-dordoigne** [AlternC/AlternC#65]
Les scripts faisant des recherches dans les fichiers de zone interprètent le nom de domaine comme une expression rationnelle : le "." correspond à n'importe quel caractère donc si par exemple on a un utilisateur coiffeur qui détient "cheveu.org", l'utilisateur communiste qui voudra réserver "che.eu.org" criera à la censure parce que son domaine sera bloqué :
```
$ echo cheveu.org |grep che.eu.org
cheveu.org

```

Il faudrait utiliser fgrep ou grep -F pour éviter cela :
```
$ echo cheveu.org |grep -F che.eu.org
$ 
```

J'ai corrigé le problème en patchant sauvagement functions_dns.sh, je vais proposer le patch directement afin que d'autres ne subissent pas le bug, mais il faudrait se poser la question de la réécriture de tout cela.

**Comment by innoticFR** [comment]
Ce patch apporte de nouveaux bugs puisque l'option -F supprime le fonctionnement normal de toute expression régulière: Voir par exemple aux lignes 98-100, le matching sur les débuts et fins de ligne avec les caractères `^` et `$`
`echo "che.eu.org" | grep -F "^che.eu.org\$"`
