### ISSUE TITLE
no TTL update on bind zone

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#67]
Debian 6
AlternC 3.1.10

Après la modification de la TTL d'une zone de 86400 à 3600 sur un domaine via l'interface web et le passage du script `/usr/lib/alternc/update_domains.sh`, le serial est bien augmenté, mais la TTL est de nouveau de 86400, aussi bien dans le fichier zone, la base MySQL que dans l'interface web.

La zone n'est pas locké (LOCKED:NO)

**Comment by innoticFR** [comment]
The TTL is defined in the first line of the zone file within the variable $TTL but there is still a default TTL value of 86400 defined in the SOA record.

The value in the SOA record will be used by pre-bind 8.2 versions.

Can you confirm that you see a value of 3600 in the first line of the file and a value of 86400 in the SOA record?

**Comment by innoticFR** [comment]
Note, the former TTL value in the SOA record is no longer used as so by Bind. RFC 2038 now considers it as the TTL used for negative answer.

I changed the comment in the file zone accordingly : 06a3e2537e9c54f3af88c836a0e0dffd9d0ed4f8

**Comment by vincib** [comment]
the template file (see innoticFR patch) is good, 
People: please let debian upgrade your template in /etc/alternc/templates/bind/*
