### ISSUE TITLE
https subdomain to panel acts as simple redirection to L_FQDN

### ISSUE THREAD

**Issue by innoticFR** [AlternC/AlternC#69]
I don't understand why we are able to configure a subdomain which points in SSL to the panel and having a virtualhost fully configurerd when the PHP code redirects to the default FQDN:

```
// Redirection si appel à https://(!fqdn)/
if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == "on" && $host != $L_FQDN) {
    header("Location: https://$L_FQDN/");
}
```

This modifications referenced to the former ticket 526 which is no longer available and was entitled "admin sql et fdqn" (see commit 6a877e1008d5a67d4c23cf44464b818baf2f3b3b)

Should we remove this test in the PHP code or should we change panel-ssl.conf to have a simple RewriteRule?

**Comment by innoticFR** [comment]
The virtualhost generated contains:

    SSLEngine On
    SSLCertificateFile %%CRT%%
    SSLCertificateKeyFile %%KEY%%
    %%CHAINLINE%%

**Comment by vincib** [comment]
dupliate of #106
