### ISSUE TITLE
[feature request] new button to reset listmaster passwd

### ISSUE THREAD

**Issue by cypriengay** [AlternC/AlternC#72]
Bonjour ! Hello!

I apologize for the noise if the following is already implemented
(I checked in the visible rather recent open and closed bugs).

In the panel of all lists created by the logged user, see screenshot below,
it would be great to have one button per mailing-list
to reset the corresponding listmaster password.
http://bradylogist.info/cgay/4a630a2bf2/AlternC-mailing-lists-panel-2016-03-17_19h33.png
Thanks a lot!

Cyprien.

**Comment by innoticFR** [comment]
This feature has already been added in commit 203c8b6c069528b458856cf0b021ecc0cc9c5f54
