### ISSUE TITLE
Potential problem with creating MySQL users that are too long

### ISSUE THREAD

**Issue by sofian** [AlternC/AlternC#74]
Because MySQL usernames seem to be based on the account name (at least in bureau.koumbit.net), if said account name is more than 16 characters is will be impossible to create new MySQL users cause they are limited to 16 characters. For example if my account name is abcdef0123456789, if I try creating a new MySQL user it will automatically append an underscore (_) which will exceed 16 chars. AlternC doesn't let me do it of course, but that means the account names length should be limited (if it isn't already).

**Comment by vincib** [comment]
Account names CAN'T be longer than 14 characters, see m_admin.php line 606
