### ISSUE TITLE
[Install jessie] Ne créé pas les repertoires des données web et mail si différents des valeurs par défaut

### ISSUE THREAD

**Issue by GanGuoLang** [AlternC/AlternC#76]
Bonjour,

Lors de l'installation, si on précise un répertoire différent pour les fichiers web et mail, l'installation ne se termine pas.
Par défaut c'est /var/www/alternc/

Il faut que les répertoires existent au préalable (ou bien les créer et relancer l'installation).

Il manque un test et la création des répertoires personnalisés.

**Comment by vincib** [comment]
Semble corrigé en 3.2.11. alternc.install fait un mkdir des dossiers $ALTERNC_HTML/[a-z0-9_]

vérifié sur une 3.2.11, ça marche
