### ISSUE TITLE
[install jessie] Apache ne se lance pas (syntaxe pour l'ancienne version)

### ISSUE THREAD

**Issue by GanGuoLang** [AlternC/AlternC#77]
Bonjour,

Apache refuse de se lancer parce que le fichier de configuration généré utilise l'ancienne syntaxe de Apache:

> Syntax error on line 45 of /etc/apache2/conf-enabled/alternc.conf:
> Either all Options must start with + or -, or no Option may.

> Server version: Apache/2.4.10 (Debian)
> Server built:   Jan  3 2016 03:50:53

**Comment by vincib** [comment]
Fixed at ea3371ae
