### ISSUE TITLE
Logs dans other_vhosts_access.log

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#79]
Pleins de logs vont se mettre dans other_vhosts_access.log

www.xxx.be:80 xxxx - - [01/May/2016:06:25:12 +0200] "GET /squelettes/img/icones/iconset_aquaticus/35x35/feed.png HTTP/1.1" 304 227 "http://www.xxx.be/proposer-un-evenement-test?var_mode=preview" "Mozilla/5.0 (Mac
intosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17"

Par exemple, pour hier

cat /var/log/alternc/sites/2*/access-20160509.log |wc -l
164041

cat /var/log/apache2/other_vhosts_access.log.1|wc -l
701779

alternc 3.2.10

**Comment by innoticFR** [comment]
Default Apache installation configures in `/etc/apache2/conf-enabled/other-vhosts-access-log.conf` a log file for virtualhosts without CustomLog directive. AlternC also defines another CustomLog to separate logs by login inside /etc/alternc/apache_logformat.conf. Both work conjointly.

If you want to remove the default Apache logs, you can type `a2disconf other-vhosts-access-log` but this will disable the ability to have a flat log file which is something sysadmin like to have when they want to do some log analysis/bug tracking.

I am not sure that it would be Debian compliant to automate this task.

---

Par défaut Apache met en place une directive CustomLog par défaut pour les VirtualHosts qui n'ont pas de CustomLog (/etc/apache2/conf-enabled/other-vhosts-access-log.conf). AlternC met en place une autre directive CustomLog pour répartir les logs en fonction du login. Les deux fonctionnent en parallèle.

Si tu veux supprimer les logs Apache par défaut, tu le peux avec la commande `a2disconf other-vhosts-access-log` mais ça t'enlèvera la possibilité d'avoir un fichier plat avec tous les logs, ce qui est bien pratique pour les admins quand on a besoin de faire de l'analyse de logs/recherche de bugs.

Je ne suis pas certain que désactiver automatiquement la config serait compatible avec la politique Debian.

**Comment by ddeenniiss** [comment]
Oups, je mettais basé sur les lignes de logs mais la rotation de other_vhosts_access.log n'est pas la même que les fichiers de logs de /var/log/alternc/sites/
