### ISSUE TITLE
[alternc-roundcube] SSL database entry not created

### ISSUE THREAD

**Issue by dotms** [AlternC/AlternC#80]
After installing the alternc-roundcube package (on Debian Wheezy 7.1) the database entry for roundcube-ssl is not created in the `domaines_type`sql table. Only roundcube is created which does http. Manually creating it in the databases makes it available since the template actually is available on disk.

+++-==============-============-============-=================================
ii  alternc-roundc 3.2.10       all          Roundcube-Webmail plugin and conf

**Comment by vincib** [comment]
This roundcube-ssl would only be created when you install (or reinstall) the alternc-ssl package, which is somehow obsoleted by Letsencrypt ... We should add support for native letsencrypt in AlternC (next Long-term-supported version I think...) in that case we will provide ssl template of course

**Comment by kent1D** [comment]
En fait j'ai eu le problème avec alternc-ssl installé, mais l'installation d'alternc-ssl est buguée.

Je fais une pull request pour résoudre ce soucis
