### ISSUE TITLE
SSL certificate for demo.alternc.org expired on 5/6/2016

### ISSUE THREAD

**Issue by CHiPs44** [AlternC/AlternC#82]
demo.alternc.org uses an invalid security certificate.
The certificate expired on 06/05/2016 23:02.
The current time is 01/06/2016 19:39.
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Please renew it !

**Comment by vincib** [comment]
fixed. Using letsencrypt now with autorenew \o/ thanks for the report !
