### ISSUE TITLE
[Install jessie] Impossible de supprimer dossiers et fichiers crées en FTP

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#83]
Un dossier crée en FTP aura les droits drwxr-sr-x+ , un fichier -rw-rw----+

Il est possible de les supprimer en FTP mais pas dans le bureau

PHP Warning:  unlink(/var/www/alternc/t/toto/twentysixteen/comments.php): Permission denied in /usr/share/alternc/panel/class/m_bro.php on line 1119

Les fichiers/dossiers crées depuis le bureau sont supprimmables.

**Comment by vincib** [comment]
non reproductible pour moi : 
uploadé un fichier en FTP, il a les droits suivants : 

root@vm5:/var/www/alternc/a/admin# getfacl compteurs 
# file: compteurs
# owner: 2000
# group: 2000
user::rw-
user:www-data:r-x		#effective:r--
user:alterncpanel:rwx		#effective:rw-
user:2000:rwx			#effective:rw-
group::rwx			#effective:rw-
group:alterncpanel:rwx		#effective:rw-
group:2000:rwx			#effective:rw-
mask::rw-
other::---

le bureau me permet bien de le supprimer.

testé aussi en créant un dossier et un fichier en FTP et en tentant de supprimer le dossier via le panel (OK)



si vous êtes en NFS, le bug #104, corrigé depuis, est surement la cause.

**Comment by vincib** [comment]
par contre en FTP on peut modifier les droits de manière suffisemment fermée (000) pour que le panel ne puisse plus accéder au dossier, dans ce cas le panel affiche un message : 

"Le dossier n'existe pas" 

si on veut aller dans le dossier

et effacer ce dossier provoque : 

26/08/2016 16:03:50 - 91.194.61.194 - CALL - admin - bro - _delete(/var/www/alternc/a/admin/test///////////////////////////////////////////) - 

J'ai corrige ce problème uniquement, pour 3.3.11 au commit 4f3604e7177ca6c06445bd34d25a51c1aeaf751a
La détection propre de dossier ou fichier à droits impossibles par le panel étant reporté au 3.3.12 cf #114
