### ISSUE TITLE
authentification phpmyadmin depuis le bureau

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#84]
L'authentification phpmyadmin depuis le bureau ne semble pas fonctionner que ce soit en 3.2.10 sous wheezy ou en 3.3.10~zznightly201606010202 sous Jessie.

**Comment by camlafit** [comment]
As tu essayé de mettre  dans /etc/apache2/conf.d/phpmyadmin.conf
<Directory /usr/share/phpmyadmin>
        AssignUserId #33 #33
        SetEnv LOGIN "33-www-data"

Il semblerait qu'apache execute phpmyadim sur un autre compte que www-data et une partie de la configuration n'est pas chargée convenablement.

**Comment by vincib** [comment]
Note : il est prévu que phpmyadmin  tourne en tant que **alterncpanel**, **pas www-data**
De plus, apache-mpm-itk ne sait pas gérer des user unix **par répertoire** (bloc <Directory>) uniquement par vhost.

cf #139 pour la suite.
