### ISSUE TITLE
REST connections to AlternC

### ISSUE THREAD

**Issue by alberto56** [AlternC/AlternC#86]
Hi,

I have an AlternC account with Koumbit and I couldn't find documentation on how to perform actions without going through the GUI. For example, is it possible to run something like:

https://path.to.alternc/api/add-email-address/me@example.com which would return something like:

    status: success
    mail: me@example.com
    password: cchwhy3ohpGFXMg58+zo3RZAWs4

? If not, is anyone actively working on this or is there interest in this? I noticed [this thread](http://dev.alternc.narkive.com/YwqD2ko4/api-rest-pour-alternc) but it seems dead.

**Comment by vincib** [comment]
The API exists, it's provided as a separated debian package : alternc-api, built when you build the main branch (currently stable-3.1)
You can use it by adding a SHAREDSECRET in the mysql alternc table for a specific user-id. This shared secret can be used to obtain an api token and use it to call any function provided by the API. 
the API does not currently provide all functions, they are in /usr/share/php/AlternC/Api/Object/

If some functions wrappers are missing, feel free to contribute from here : https://github.com/AlternC/AlternC/tree/stable-3.1/lib/Alternc/Api
