### ISSUE TITLE
 service: command not found

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#88]
Sous wheezy, alternc 3.2.10

A chaque modification de domaine

/usr/lib/alternc/update_domains.sh: line 164: service: command not found

**Comment by nahuelange** [comment]
À ma connaissance c'est un problème connu, et corrigé dans la nightly

**Comment by ddeenniiss** [comment]
Yep, c'est ici. https://github.com/AlternC/AlternC/commit/77199b978845f6cf073c00df7b9cd4e82bcc883d
