### ISSUE TITLE
BDD non accessible

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#9]
Suite à la création d'une bdd et d'un utilisateur, la bdd n'est pas accessible ( par exemple via la commande `mysql -u USER -p`).

Le problème se situe dans le champ `Host` de la table `User` (base de données `mysql`) qui a comme valeur `%` et non `localhost`.

Correction possible : 

```
mysql> update user set Host="localhost" where User="USER";
```

Le véritable problème provient sans doute de la table `db` de la base `alternc`, et plus précisément de `client` : 

```
mysql> select * from db;

| id | name    | host      | login  | password   | client |
+----+---------+-----------+--------+------------+--------+
|  1 | Default | 127.0.0.1 | sysusr | xxxxxxx | %      |
+----+---------+-----------+--------+------------+--------+
```

debian wheezy
alternc                          3.2.8
alternc-api                      3.2.8
ialternc-roundcube                3.2.8
ialternc-ssl                      3.2.8

**Comment by vincib** [comment]
Pas réussi (malgré de nombreux tests) à reproduire le problème. S'il se reproduit, rouvrir le ticket

entre 3.1.8 et 3.1.9, j'ai modifié mysql.sh pour qu'il ne plante pas lors de l'injection du schéma. Cela a probablement corrigé ce bug là aussi.
