### ISSUE TITLE
Le nom de domaine n'a pas été trouvé dans la base whois 

### ISSUE THREAD

**Issue by ddeenniiss** [AlternC/AlternC#95]
Impossible d'ajouter un domaine si l'option vérifier le DNS primaire dans la base WHOIS est activée

Alternc 3.2.10 sous wheezy

**Comment by innoticFR** [comment]
Il faudrait surtout ne plus chercher dans la base whois

`dig +trace +short -t ns` donne des résultats plus fiables, plus génériques, et plus facilement analysables

**Comment by nahuelange** [comment]
Genre utiliser http://php.net/manual/fr/function.dns-get-record.php ?

**Comment by ddeenniiss** [comment]
Si y a moyen de patcher ça facilement, je suis preneur d'une solution.

**Comment by nahuelange** [comment]
```
<?php
var_dump(dns_get_record('alternc.org', DNS_NS));
?>
```
Retourne ça:
```
array(2) {
  [0]=>
  array(5) {
    ["host"]=>
    string(11) "alternc.org"
    ["class"]=>
    string(2) "IN"
    ["ttl"]=>
    int(3600)
    ["type"]=>
    string(2) "NS"
    ["target"]=>
    string(20) "primary.heberge.info"
  }
  [1]=>
  array(5) {
    ["host"]=>
    string(11) "alternc.org"
    ["class"]=>
    string(2) "IN"
    ["ttl"]=>
    int(3600)
    ["type"]=>
    string(2) "NS"
    ["target"]=>
    string(22) "secondary.heberge.info"
  }
}
```

Le patch ne devrait pas être dur à faire

**Comment by innoticFR** [comment]
Ca serait trop beau pour être vrai.

`dns_get_record()` interroge le serveur de nom déclaré auprès du registre. Dans notre cas, ce serveur, c'est théoriquement le serveur sur lequel le nom de domaine n'est pas encore installé. 

Par exemple, il faut avoir une fonction qui puisse renvoyer les DNS du nom de domaine "a8.be". Ils sont présents dans le whois, dans `dig +trace +short -t ns` mais pas dans un `dig` standard ni dans le résultat de `dns_get_record()`

**Comment by nahuelange** [comment]
Le `dig +trace +short -t ns` semble faire pareil (interroger les NS du domaine et pas les ns root)

**Comment by innoticFR** [comment]
Oui faut enlever le `+short`, mais de toute façon, c'est pas non plus la panacée. En fait il va interroger tous les serveurs NS depuis les serveurs racines, donc il finira avec un timeout sur le serveur du domaine, ce qui est sale.

Une autre solution serait d'avoir pour chaque TLD les DNS du registre liés à l'extension 
Par exemple : `dig -t ns a8.be @a.ns.dns.be` renvoie la réponse immédiatement

Mais c'est tout de suite beaucoup moins générique en fait...

**Comment by innoticFR** [comment]
Après avoir tourné en rond, mon avis sur la question :

 - on cherche surtout à ne pas installer un domaine hébergé ailleurs. Donc on peut déjà répondre négativement dès lors que `dns_get_record()` renvoie d'autres noms de serveurs.

 - on peut répondre positivement s'il renvoie les bons noms de serveurs (même si c'est pas cohérent puisque le domaine n'est pas installé)

 - on peut obtenir les noms des serveurs du domaine a8.be avec la commande
`dig +noall +time=1 +tries=1 +trace -t soa a8.be | awk '{if ($1=="a8.be.") {print $5}}'`
mais elle implique un léger délai plus important que le whois.
Le whois semble donc un moyen rapide mais difficile à parser

- il doit être possible soit de recréer l'équivalent d'un `dig +trace` en php, soit d'utiliser la liste des NS propres à chaque extension (liste qui peut se fabriquer automatiquement). Mais pour rester simple il faudrait partir du principe que les serveurs NS que l'on interroge ne tombent jamais en panne.

- Mais à terme il serait bien d'avoir une solution flexible qui n'oblige pas à insérer les extensions voulues une par une.

**Comment by nahuelange** [comment]
Très bonne idée, après l'utilisateur n'ajoute pas 1 domaine par seconde, et il pourrait y avoir un système «semi asynchrone» (faire  du js pour afficher un spinner le temps de checker les NS par exemple)

**Comment by vincib** [comment]
We could replace the WHOIS function by 2 (very fast) DIGS as follow : 
`dig ns .com` (the tld, could be .co.uk ...) 
retrieve the NS and the IP addresses, and dereference one of them
`dig ns thedomain.com @one-of-the-IPs-returned-by-the-first-dig`
and the answer should be our NS.
we can do that with 2 calls to exec() and parsing of the output made by PHP (would be faster and easier to debug than awk |grep|...

If you agree with that, I can do that for 3.2.11, considering this as an interface bug.

Also, we could consider any NON-defined TLDs as being "check DNS in whois" by default, instead of "forbidden"

**Comment by innoticFR** [comment]
@vincib You're perfectly right. So, assuming we add domain 'example.eu.org'
`dig +short ns eu.org` retrieve the NS we ask for authoritative name servers. That seems fine and generic. I think that could be the process used by default for any TLD not present in the `tld` table.

This will fail with second sublevel delegation (eg. herisson.nom.fr) `herisson.nom` is declared in the `fr` zone, so `dig +short ns nom.fr` retrieves nothing (although `.fr` extension is already a particular requiring the zone to be present on the server case, see below). For such similar cases, the whois could be a fallback.

And the only extensions requiring to be in the `tld` table would be specific extensions which are forbidden, or have to be inserted without any check (like the aforementioned `.fr` extension)

**Comment by camlafit** [comment]
Hello

Also we can use a dedicated library to get whois :
* https://sourceforge.net/projects/phpwhois/
* https://github.com/regru/php-whois
* https://github.com/phpWhois/phpWhois/

First look a complete solution, second looks light and easy to patch to add specific tld (it's an independent json file).

**Comment by innoticFR** [comment]
Using the "whois" database is the problem we attempt to avoid.

They provide results only for main level domain names, are not always accurate, and there's no standard nor obligation for whois content : 
  - for instance the whois for `es` extension is http only,
  - no DNS servername  in `.no` whois (eg. whois norid.no)

**Comment by vincib** [comment]
Closed, see #195 for a formal evolution proposal
