### ISSUE TITLE
popimap-log-login generating table lock

### ISSUE THREAD

**Issue by innoticFR** [AlternC/AlternC#96]
Login of last connection in IMAP and POP is locking the tables (server with 20k mailboxes).

Access to panel becoming slow. (40s)

Commenting the UPDATE has an immediate effect on performances.

**Comment by fser** [comment]
How about switching from MyISAM to InoDB for this table?

**Comment by innoticFR** [comment]
I might be wrong but MySQL views are neither MyISAM nor InnoDB. They are just abstraction layers

**Comment by fser** [comment]
My bad, I was only reading your bug report talking about locking the table. That misguided me. I should have checked.

**Comment by innoticFR** [comment]
In you were right, I was thinking about another ticket.

The update uses 3 tables in MyISAM 
    update address a, domaines d, mailbox m set ...

**Comment by innoticFR** [comment]
Have made the modification today on the installation. It seems that switching engine has positive impact

**Comment by vincib** [comment]
We could add this alter table to the 3.X.11 release ?
maybe switch all AlternC tables to InnoDB, which locks by columns & rows instead of tables when updating. Knowing AlternC's panel code, I see no problem with that.
