### ISSUE TITLE
dovecot_view problems (updating quotas)

### ISSUE THREAD

**Issue by innoticFR** [AlternC/AlternC#98]
It seems that under high load dovecot_view causes some lock situation:

     Warning: read(/var/run/dovecot/dict): dict lookup took 9 seconds

Also, I don't know if it's caused by my configuration or the above locking problem but I have some errors:

     dict: Error: sql dict: commit failed: Can not delete from join view 'alternc.dovecot_view'

http://wiki2.dovecot.org/Quota/Dict
http://dev.mysql.com/doc/refman/5.7/en/view-updatability.html (*"The table or tables to be deleted from in a DELETE statement must be merged views. "*).
Also I'm not sure that we want data to be deleted...

Temporary fixing this on my installation by creating a dovecot_quota table

     CREATE TABLE dovecot_quota (
      user varchar(1000) not null,
      quota_dovecot bigint not null default 0,
      nb_messages integer not null default 0,
      primary key (user)
     );

**Comment by innoticFR** [comment]
it seems again that changing the tables used by the view to innodb has good effect on performance, but we still have (fortunately to be honest) the message
<code>dovecot: dict: Error: sql dict: commit failed: Can not delete from join view 'alternc.dovecot_view'</code>

**Comment by vincib** [comment]
Fixed while fixing tables to InnoDB. The commit failed message can't be prevented ... found no solution against it, although it's not a problem per se...
